// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Moderately AI Inc.

//! The release-tier gate: the single enforced check that release claims match the
//! machine-readable support tiers.
//!
//! The tier assignment is the source of truth (`BuiltinDialect::support_tier` /
//! `ProductSurface::support_tier` in `squonk`). This module enforces the two
//! invariants over it and generates the human-facing table from the same data, so a
//! stable claim without an authoritative source of truth — or a docs table that has
//! drifted from the code — fails the build.

use squonk::BuiltinDialect;
use squonk::ast::dialect::SupportEvidence;
use squonk::dialect::ProductSurface;

/// Render one [`SupportEvidence`] as a compact `kind — detail` table cell.
fn evidence_cell(evidence: SupportEvidence) -> String {
    match evidence {
        SupportEvidence::EngineDifferential {
            engine,
            version,
            method,
        } => format!("engine_differential — {engine} {version}; {method}"),
        SupportEvidence::StandardReference { note } => format!("standard_reference — {note}"),
        SupportEvidence::ContractGate { artifact, note } => {
            format!("contract_gate — {artifact}; {note}")
        }
        SupportEvidence::Comparison { tool, note } => format!("comparison — {tool}; {note}"),
        SupportEvidence::DocumentationDerived { note } => {
            format!("documentation_derived — {note}")
        }
        SupportEvidence::Constructed { note } => format!("constructed — {note}"),
    }
}

/// Collapse the hard-wrapped `&'static str` notes (authored with `\`-continued
/// string literals) to single-spaced text so the generated table has one line per row.
fn one_line(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// Generate the full `docs/support-tiers.md` document from the tier assignment — the
/// same table the invariant gate reads, so the doc can never drift from the code.
pub fn render_support_tiers_doc() -> String {
    let mut out = String::new();
    out.push_str(
        "<!-- GENERATED by squonk-conformance `support_tiers`. Do not edit by hand: \
         change `BuiltinDialect::support_tier` / `ProductSurface::support_tier` and \
         regenerate with `UPDATE_SUPPORT_TIERS=1 cargo nextest run -p squonk-conformance \
         support_tier`. -->\n\n",
    );
    out.push_str("# Supported surface and dialect tiers\n\n");
    out.push_str(
        "Every shipped dialect preset and optional product surface carries a release-contract \
         **support tier**. The tier is a coarser, separate axis from the per-feature `Maturity` \
         (which asks whether a single `FeatureSet` knob's API is stable): it states how strong \
         the *parity evidence* for the whole preset is, and therefore what the stable release \
         promises for it.\n\n",
    );
    out.push_str("## Tiers\n\n");
    out.push_str(
        "- **stable** — production-ready; backed by an *authoritative* source of truth \
         (a real engine/reference-parser differential, the SQL standard itself, or a frozen \
         drift-gated contract artifact) and held to it by an enforced gate.\n",
    );
    out.push_str(
        "- **preview** — usable and API-stable, but not a full engine-parity guarantee: a \
         differential/comparison oracle wired at partial coverage or outside the default gate, \
         or a preset constructed to match no single engine by design.\n",
    );
    out.push_str(
        "- **experimental** — documentation-derived only, with no differential oracle wired \
         (typically because engine acquisition is blocked). Behaviour may diverge and change \
         without notice.\n\n",
    );

    out.push_str("## Dialect presets\n\n");
    out.push_str("| Preset | Tier | Source of truth |\n");
    out.push_str("| --- | --- | --- |\n");
    for dialect in BuiltinDialect::ALL {
        out.push_str(&format!(
            "| {} | {} | {} |\n",
            dialect.name(),
            dialect.support_tier().id(),
            one_line(&evidence_cell(dialect.support_evidence())),
        ));
    }

    out.push_str("\n## Product surfaces\n\n");
    out.push_str("| Surface | Tier | Source of truth |\n");
    out.push_str("| --- | --- | --- |\n");
    for surface in ProductSurface::ALL {
        out.push_str(&format!(
            "| {} | {} | {} |\n",
            surface.id(),
            surface.support_tier().id(),
            one_line(&evidence_cell(surface.support_evidence())),
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use squonk::ast::dialect::SupportTier;
    use std::path::{Path, PathBuf};

    /// `docs/support-tiers.md`, resolved from this crate's manifest dir (the workspace
    /// root is one level up from `conformance/`).
    fn doc_path() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../docs/support-tiers.md")
    }

    /// The core release invariant: a `Stable` tier must cite authoritative evidence.
    ///
    /// This is what stops a documentation-derived or comparison-only preset from being
    /// advertised as stable. The *live* backing for the engine-differential stable
    /// dialects (that the named oracle actually ran) is the nightly parity guard
    /// (`oracle-nightly.yml`); this gate keeps the metadata claim honest at build time.
    #[test]
    fn stable_tier_requires_authoritative_evidence() {
        for dialect in BuiltinDialect::ALL {
            if dialect.support_tier() == SupportTier::Stable {
                assert!(
                    dialect.support_evidence().is_authoritative(),
                    "dialect `{}` is Stable but cites non-authoritative evidence: {:?}",
                    dialect.name(),
                    dialect.support_evidence(),
                );
            }
        }
        for surface in ProductSurface::ALL {
            if surface.support_tier() == SupportTier::Stable {
                assert!(
                    surface.support_evidence().is_authoritative(),
                    "product surface `{}` is Stable but cites non-authoritative evidence: {:?}",
                    surface.id(),
                    surface.support_evidence(),
                );
            }
        }
    }

    /// The conformance build compiles `squonk` with `full`, so every shipped
    /// dialect is present and tiered here. A missing tier is a compile error (the
    /// `support_tier`/`support_evidence` matches are total), so this only guards the
    /// count against a silently-dropped preset.
    #[test]
    fn every_shipped_dialect_and_surface_is_tiered() {
        assert_eq!(
            BuiltinDialect::ALL.len(),
            14,
            "expected 14 shipped presets under `full`; update this gate and the tier table \
             when the shipped set changes",
        );
        assert_eq!(ProductSurface::ALL.len(), 4);
    }

    /// Docs are generated from the same table: the checked-in `docs/support-tiers.md`
    /// must equal the render, so a tier change forces a reviewed doc diff. Regenerate
    /// with `UPDATE_SUPPORT_TIERS=1 cargo nextest run -p squonk-conformance support_tier`.
    #[test]
    fn support_tier_doc_is_current() {
        let rendered = render_support_tiers_doc();
        let path = doc_path();
        if std::env::var_os("UPDATE_SUPPORT_TIERS").is_some() {
            std::fs::write(&path, &rendered).expect("write support-tiers doc");
            return;
        }
        let on_disk = std::fs::read_to_string(&path).unwrap_or_default();
        assert_eq!(
            on_disk, rendered,
            "docs/support-tiers.md is stale; regenerate with UPDATE_SUPPORT_TIERS=1 \
             cargo nextest run -p squonk-conformance support_tier",
        );
    }
}
