# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Moderately AI Inc.

version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
