# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Moderately AI Inc.

# Four positional args is enough ambiguity to warrant a named args/request struct
# (clippy counts `self`, so this fires at four user-visible arguments).
too-many-arguments-threshold = 5
