// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Moderately AI Inc.

//! Emit a generated node-id walk: a `Visit` collector that records every
//! id-bearing node's `Meta` (its `NodeId` and source `Span`).
//!
//! WHY this is generated (ADR-0013): the node-identity invariant test
//! (`crates/squonk/src/parser/node_id.rs`) must cover *every* node that
//! carries a `NodeId` (ADR-0002), or a new node type silently escapes the
//! uniqueness/non-zero invariant. Hand-registering the id-bearing node set in
//! that test is exactly the drift this xtask exists to remove — the same shape
//! that already let `Spanned` drift into empty-span holes. The override set is
//! derived from the one fact that defines id-bearing-ness — a `meta: Meta` field
//! — and descent reuses the generated `Visit` traversal, so the walk stays
//! exhaustive without a hand-maintained list.
//!
//! A struct node exposes `meta` directly; a metadata-bearing enum carries `meta`
//! on every variant, so its arm is an exhaustive `match` (a future variant that
//! forgets `meta` fails to compile here). Nodes without `meta` — `ObjectName`,
//! operator/tag enums — record nothing and keep the default walk, which still
//! reaches their id-bearing children.

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::{ItemEnum, ItemStruct};

use crate::schema::{NodeItem, Schema, enum_has_meta, snake_case, struct_has_meta};

const HEADER: &str = "\
//! @generated by `squonk-sourcegen`; do not edit by hand.
//! Regenerate with `cargo run -p squonk-sourcegen`.

#![allow(clippy::all)]

";

/// Render the full, formatted `generated/node_id_walk.rs` contents.
pub(crate) fn render(schema: &Schema) -> String {
    let overrides = schema.items.iter().filter_map(emit_override);
    let tokens = quote! {
        use crate::ast::*;
        use crate::generated::visit::{self, Visit};
        use crate::vocab::Meta;

        /// Collects every id-bearing node's `Meta` from a parsed tree by reusing the
        /// generated `Visit` traversal: each override records the visited node's
        /// `meta`, then delegates to the matching generated `walk_*` to descend into
        /// children.
        ///
        /// Recording `Meta` — not just `NodeId` — lets one walk serve both whole-tree
        /// identity invariants: unique nonzero ids and non-synthetic spans.
        ///
        /// Fixed to the stock `NoExt` extension (like the node-identity test it feeds):
        /// the invariant holds over the production AST, and a concrete extension keeps
        /// each generated `walk_*` call's `X` inferable for childless leaf nodes.
        #[derive(Default)]
        pub struct NodeIdWalk {
            /// One entry per id-bearing node, in visitation order.
            pub metas: Vec<Meta>,
        }

        impl<'ast> Visit<'ast, NoExt> for NodeIdWalk {
            #(#overrides)*
        }
    };
    let file = syn::parse2::<syn::File>(tokens).expect("generated node-id walk parses as a file");
    format!(
        "{}{HEADER}{}",
        crate::license_header::block(crate::license_header::Comment::Slash),
        prettyplease::unparse(&file)
    )
}

/// Emit the `visit_*` override for one id-bearing node, or `None` for a node that
/// carries no `Meta` (`ObjectName`, operator/tag enums) — those keep the default
/// walk, which still descends into their id-bearing children.
fn emit_override(item: &NodeItem) -> Option<TokenStream> {
    match item {
        NodeItem::Struct(s) if struct_has_meta(s) => Some(emit_struct_override(s)),
        NodeItem::Enum(e) if enum_has_meta(e) => Some(emit_enum_override(e)),
        NodeItem::Struct(_) | NodeItem::Enum(_) => None,
    }
}

/// A struct node exposes `meta` directly: record it, then walk its children.
fn emit_struct_override(s: &ItemStruct) -> TokenStream {
    let name = &s.ident;
    let (method, walk) = idents(name);
    let ty = node_ty(name, &s.generics);
    quote! {
        fn #method(&mut self, node: &'ast #ty) {
            self.metas.push(node.meta);
            visit::#walk(self, node);
        }
    }
}

/// A metadata-bearing enum carries `meta` on every variant, so the arm is an
/// exhaustive `match`: a future variant added without `meta` fails to compile
/// here, flagging a node kind that would otherwise dodge the identity invariant.
fn emit_enum_override(e: &ItemEnum) -> TokenStream {
    let name = &e.ident;
    let (method, walk) = idents(name);
    let ty = node_ty(name, &e.generics);
    let arms = e.variants.iter().map(|variant| {
        let vname = &variant.ident;
        quote! { #name::#vname { meta, .. } => *meta, }
    });
    quote! {
        fn #method(&mut self, node: &'ast #ty) {
            self.metas.push(match node {
                #(#arms)*
            });
            visit::#walk(self, node);
        }
    }
}

/// The override's parameter type at the stock extension: a node generic over the
/// extension is instantiated at `NoExt` (`Expr<NoExt>`), matching the `Visit<NoExt>`
/// trait method it overrides; a non-generic node renders bare (`Ident`).
fn node_ty(name: &syn::Ident, generics: &syn::Generics) -> TokenStream {
    let args = generics
        .type_params()
        .map(|_| quote! { NoExt })
        .collect::<Vec<_>>();
    if args.is_empty() {
        quote! { #name }
    } else {
        quote! { #name<#(#args),*> }
    }
}

/// The `(visit_*, walk_*)` idents for a node, matching the generated `Visit` trait.
fn idents(name: &syn::Ident) -> (syn::Ident, syn::Ident) {
    let suffix = snake_case(&name.to_string());
    (
        format_ident!("visit_{suffix}"),
        format_ident!("walk_{suffix}"),
    )
}

#[cfg(test)]
mod tests {
    use std::collections::{BTreeMap, BTreeSet};

    use syn::parse_quote;

    use super::*;

    /// The headline acceptance, demonstrated end to end: a brand-new id-bearing node
    /// type added to the schema gains its `visit_*` override with no edit to this
    /// emitter (and none to the node-identity test that consumes it). The override
    /// set is computed from the node's `meta: Meta` shape, so coverage extends to the
    /// new node automatically, with no hand-registration step to maintain (ADR-0002,
    /// ADR-0013).
    ///
    /// `render` reads only `schema.items`, so a minimal synthetic schema isolates the
    /// emitter from the live AST.
    #[test]
    fn a_new_id_bearing_node_is_overridden_automatically() {
        let new_struct: ItemStruct = parse_quote! {
            struct BrandNewNode {
                child: Expr,
                meta: Meta,
            }
        };
        let new_enum: ItemEnum = parse_quote! {
            enum BrandNewChoice {
                First { value: Expr, meta: Meta },
                Second { meta: Meta },
            }
        };
        let schema = Schema {
            items: vec![NodeItem::Struct(new_struct), NodeItem::Enum(new_enum)],
            families: BTreeMap::new(),
            item_names: BTreeSet::new(),
            spanned: BTreeSet::new(),
            reachable: BTreeSet::new(),
        };

        let rendered = render(&schema);

        // The struct node records its `meta` directly, then walks its children.
        assert!(
            rendered.contains("fn visit_brand_new_node(&mut self, node: &'ast BrandNewNode)"),
            "new struct node is missing its override",
        );
        assert!(rendered.contains("self.metas.push(node.meta);"));
        // The enum node records the visited variant's `meta` via an exhaustive match.
        assert!(
            rendered.contains("fn visit_brand_new_choice("),
            "new enum node is missing its override",
        );
        assert!(rendered.contains("BrandNewChoice::First { meta, .. } => *meta,"));
        assert!(rendered.contains("BrandNewChoice::Second { meta, .. } => *meta,"));
    }

    /// The strongest form of the auto-coverage guarantee: the generated walk
    /// overrides EXACTLY the id-bearing node set — every node carrying `meta: Meta`,
    /// and nothing else. The override set is derived from the same `has_meta` shape
    /// that defines id-bearing-ness, so a newly added id-bearing node type is
    /// overridden — hence covered by the node-identity invariant test — the moment
    /// it is regenerated, with no hand-registered list to drift (ADR-0002, ADR-0013).
    #[test]
    fn override_set_equals_id_bearing_node_set() {
        let schema = Schema::load();
        let rendered = render(&schema);

        let id_bearing: BTreeSet<String> = schema
            .items
            .iter()
            .filter(|item| match item {
                NodeItem::Struct(s) => struct_has_meta(s),
                NodeItem::Enum(e) => enum_has_meta(e),
            })
            .map(NodeItem::name)
            .collect();

        // A non-trivial schema: many id-bearing nodes, not a degenerate handful.
        assert!(
            id_bearing.len() > 100,
            "expected many id-bearing nodes, found {}",
            id_bearing.len(),
        );

        // Every id-bearing node has a `visit_*` override.
        for name in &id_bearing {
            let method = format!("fn visit_{}(", snake_case(name));
            assert!(
                rendered.contains(&method),
                "id-bearing node `{name}` is missing its generated override",
            );
        }
        // ...and nothing else does: the override count equals the id-bearing count.
        let override_count = rendered.matches("fn visit_").count();
        assert_eq!(
            override_count,
            id_bearing.len(),
            "the walk must override exactly the id-bearing node set",
        );
    }
}
