// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Moderately AI Inc.

//! Emit Python `TypedDict` declarations for the serde JSON AST.

use std::collections::BTreeSet;

use syn::{Fields, GenericArgument, ItemEnum, ItemStruct, PathArguments, Type, TypePath};

use crate::schema::{NodeItem, Schema, extension_generics};

const HEADER: &str = "\
# @generated by `squonk-sourcegen` -- do not edit by hand.\n\
#\n\
# Complete Python declarations for the serde JSON AST.\n\
# Regenerate with `cargo run -p squonk-sourcegen`.\n\
\n";

pub(crate) fn render(schema: &Schema) -> String {
    let mut out = crate::license_header::block(crate::license_header::Comment::Hash);
    out.push_str(HEADER);
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("from typing import Literal, Never, TypeAlias, TypedDict, Union\n\n");
    out.push_str("Symbol: TypeAlias = int\nNodeId: TypeAlias = int\n");
    out.push_str("AstNodeJson: TypeAlias = dict[str, object]\n\n");
    out.push_str("class SpanJson(TypedDict):\n    start: int\n    end: int\n\n");
    out.push_str("class MetaJson(TypedDict):\n    span: SpanJson\n    node_id: NodeId\n\n");

    for item in schema
        .items
        .iter()
        .filter(|item| schema.is_reachable(&item.name()))
    {
        match item {
            NodeItem::Struct(item) => render_struct(schema, item, &mut out),
            NodeItem::Enum(item) => render_enum(schema, item, &mut out),
        }
        out.push('\n');
    }

    out.truncate(out.trim_end().len());
    out.push('\n');
    out
}

fn render_struct(schema: &Schema, item: &ItemStruct, out: &mut String) {
    let name = format!("{}Json", item.ident);
    let generics = extension_generics(&item.generics);
    match &item.fields {
        Fields::Named(fields) => {
            render_typed_dict(
                &name,
                fields.named.iter().map(|field| {
                    (
                        serde_name(field.ident.as_ref().expect("named field")),
                        py_type(schema, &field.ty, &generics),
                    )
                }),
                out,
            );
        }
        Fields::Unnamed(fields) => {
            let types = fields
                .unnamed
                .iter()
                .map(|field| py_type(schema, &field.ty, &generics))
                .collect::<Vec<_>>();
            let ty = if types.len() == 1 {
                types[0].clone()
            } else {
                format!("tuple[{}]", types.join(", "))
            };
            out.push_str(&format!("{name}: TypeAlias = {ty}\n"));
        }
        Fields::Unit => out.push_str(&format!("class {name}(TypedDict):\n    pass\n")),
    }
}

fn render_enum(schema: &Schema, item: &ItemEnum, out: &mut String) {
    let enum_name = item.ident.to_string();
    let name = format!("{enum_name}Json");
    if enum_name == "NoExt" || item.variants.is_empty() {
        out.push_str(&format!("{name}: TypeAlias = Never\n"));
        return;
    }

    let generics = extension_generics(&item.generics);
    let mut members = Vec::new();
    for variant in &item.variants {
        let variant_name = variant.ident.to_string();
        match &variant.fields {
            Fields::Unit => members.push(format!("Literal[{variant_name:?}]")),
            Fields::Named(fields) => {
                let payload = format!("{enum_name}{variant_name}PayloadJson");
                render_typed_dict(
                    &payload,
                    fields.named.iter().map(|field| {
                        (
                            serde_name(field.ident.as_ref().expect("named field")),
                            py_type(schema, &field.ty, &generics),
                        )
                    }),
                    out,
                );
                out.push('\n');
                let wrapper = format!("{enum_name}{variant_name}Json");
                render_typed_dict(&wrapper, [(variant_name.clone(), payload)], out);
                out.push('\n');
                members.push(wrapper);
            }
            Fields::Unnamed(fields) => {
                let types = fields
                    .unnamed
                    .iter()
                    .map(|field| py_type(schema, &field.ty, &generics))
                    .collect::<Vec<_>>();
                let payload = if types.len() == 1 {
                    types[0].clone()
                } else {
                    format!("tuple[{}]", types.join(", "))
                };
                let wrapper = format!("{enum_name}{variant_name}Json");
                render_typed_dict(&wrapper, [(variant_name.clone(), payload)], out);
                out.push('\n');
                members.push(wrapper);
            }
        }
    }
    out.push_str(&format!("{name}: TypeAlias = Union[\n"));
    for member in members {
        out.push_str(&format!("    {member},\n"));
    }
    out.push_str("]\n");
}

fn render_typed_dict(
    name: &str,
    fields: impl IntoIterator<Item = (String, String)>,
    out: &mut String,
) {
    out.push_str(&format!("{name} = TypedDict({name:?}, {{\n"));
    for (field, ty) in fields {
        // String annotations keep declarations importable regardless of source order,
        // while functional TypedDict syntax permits serialized keys such as `from`.
        out.push_str(&format!("    {field:?}: {ty:?},\n"));
    }
    out.push_str("})\n");
}

fn py_type(schema: &Schema, ty: &Type, generics: &BTreeSet<String>) -> String {
    match ty {
        Type::Path(TypePath { qself: None, path }) => {
            let segment = path.segments.last().expect("path segment");
            let name = segment.ident.to_string();
            match name.as_str() {
                "Box" => py_type(schema, single_type_arg(segment), generics),
                "Option" => format!(
                    "{} | None",
                    py_type(schema, single_type_arg(segment), generics)
                ),
                "Vec" | "ThinVec" => format!(
                    "list[{}]",
                    py_type(schema, single_type_arg(segment), generics)
                ),
                "bool" => "bool".to_owned(),
                "u8" | "u16" | "u32" | "u64" | "usize" | "i8" | "i16" | "i32" | "i64" | "isize" => {
                    "int".to_owned()
                }
                "String" | "str" => "str".to_owned(),
                "Symbol" | "FoldedSymbol" | "NodeId" => "int".to_owned(),
                "Span" => "SpanJson".to_owned(),
                "Meta" => "MetaJson".to_owned(),
                other if generics.contains(other) => "NoExtJson".to_owned(),
                // Named declarations remain exhaustive, but embedding them recursively
                // makes mypy and Pyright expand the entire cyclic AST graph at every
                // consumer import. Child-node edges intentionally use the bounded
                // traversal shape; users can annotate a known node with its generated
                // declaration when they need field-level precision.
                other if schema.is_reachable(other) || schema.is_ast_item(other) => {
                    "AstNodeJson".to_owned()
                }
                other => panic!("cannot map Rust AST type `{other}` to Python"),
            }
        }
        Type::Tuple(tuple) => {
            let elements = tuple
                .elems
                .iter()
                .map(|item| py_type(schema, item, generics))
                .collect::<Vec<_>>();
            if elements.is_empty() {
                "tuple[()]".to_owned()
            } else {
                format!("tuple[{}]", elements.join(", "))
            }
        }
        Type::Reference(reference) => py_type(schema, &reference.elem, generics),
        Type::Array(array) => format!("list[{}]", py_type(schema, &array.elem, generics)),
        Type::Slice(slice) => format!("list[{}]", py_type(schema, &slice.elem, generics)),
        Type::Group(group) => py_type(schema, &group.elem, generics),
        Type::Paren(paren) => py_type(schema, &paren.elem, generics),
        _ => panic!("cannot map unsupported Rust AST type shape to Python"),
    }
}

fn serde_name(ident: &syn::Ident) -> String {
    let name = ident.to_string();
    name.strip_prefix("r#").unwrap_or(&name).to_owned()
}

fn single_type_arg(segment: &syn::PathSegment) -> &Type {
    let PathArguments::AngleBracketed(args) = &segment.arguments else {
        panic!("{} must carry one type argument", segment.ident);
    };
    args.args
        .iter()
        .find_map(|arg| match arg {
            GenericArgument::Type(ty) => Some(ty),
            _ => None,
        })
        .unwrap_or_else(|| panic!("{} must carry one type argument", segment.ident))
}
