// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Moderately AI Inc.

//! Emit render-shape skeletons that make renderer drift visible.

use std::collections::BTreeMap;

use proc_macro2::{Span, TokenStream};
use quote::{ToTokens, format_ident, quote};
use syn::{Fields, GenericParam};

use crate::descent::{DescentEmitter, Mutability, item_ty};
use crate::schema::{NodeItem, Schema, WalkTarget, snake_case};

const HEADER: &str = "\
//! @generated by `squonk-sourcegen`; do not edit by hand.
//! Regenerate with `cargo run -p squonk-sourcegen`.

#![allow(dead_code)]
#![allow(clippy::all)]

";

pub(crate) fn render(schema: &Schema) -> String {
    let functions = schema
        .items
        .iter()
        .filter(|item| schema.is_reachable(&item.name()))
        .map(|item| emit_shape_fn(item, schema));
    let fingerprints = family_fingerprints(schema)
        .into_iter()
        .map(|(family, hash)| {
            let const_ident = family_const_ident(&family);
            let literal = fingerprint_literal(hash);
            quote! {
                pub(crate) const #const_ident: RenderShapeFingerprint<#literal> =
                    RenderShapeFingerprint;
            }
        });
    let tokens = quote! {
        use crate::ast::*;

        pub(crate) struct RenderShapeFingerprint<const VALUE: u64>;

        #(#fingerprints)*

        #(#functions)*

        fn render_shape_extension<X: Extension>(node: &X) {
            touch(node);
        }

        fn touch<T: ?Sized>(_value: &T) {}
    };
    let file =
        syn::parse2::<syn::File>(tokens).expect("generated render skeleton parses as a file");
    format!(
        "{}{HEADER}{}",
        crate::license_header::block(crate::license_header::Comment::Slash),
        prettyplease::unparse(&file)
    )
}

/// The per-family render-shape fingerprints, one per `ast/*.rs` source file, in a
/// stable (family-sorted) order.
///
/// The partition is keyed by the source file each node type is defined in — the
/// AST author's own module boundary — rather than a hand-maintained grouping map
/// that could silently drift from the code. Every struct/enum parsed from a file
/// feeds that file's hash (reachable render node or not), so the union of the
/// family hashes fingerprints the whole AST shape exactly as the old single
/// `CURRENT_RENDER_SHAPE` did. Splitting changes only WHICH const moves on a
/// shape change: an edit to `ast/expr.rs` moves `CURRENT_RENDER_SHAPE_EXPR`
/// alone, so two agents touching disjoint files (`expr.rs` vs `ddl.rs`) move
/// disjoint pin lines in `render/nodes.rs` and merge without conflict, while a
/// genuine same-file collision still conflicts loudly on the one shared pin.
fn family_fingerprints(schema: &Schema) -> Vec<(String, u64)> {
    let mut by_family: BTreeMap<&str, Vec<&NodeItem>> = BTreeMap::new();
    for item in &schema.items {
        by_family
            .entry(schema.family_of(&item.name()))
            .or_default()
            .push(item);
    }
    by_family
        .into_iter()
        .map(|(family, items)| (family.to_owned(), shape_fingerprint(items)))
        .collect()
}

/// The `CURRENT_RENDER_SHAPE_<FAMILY>` const identifier for a source-file family.
fn family_const_ident(family: &str) -> syn::Ident {
    format_ident!("CURRENT_RENDER_SHAPE_{}", family.to_ascii_uppercase())
}

fn emit_shape_fn(item: &NodeItem, schema: &Schema) -> TokenStream {
    let name = item.name();
    let fn_name = shape_ident(&name);
    let ty = item_ty(item);
    let emitter = DescentEmitter {
        // The skeleton only ever reads, so containers unwrap shared.
        mutability: Mutability::Shared,
        leaf: &|target, accessor| call_target(target, accessor),
        // A non-node field is touched so the destructuring binding is used.
        fallback: &|accessor| quote! { touch(#accessor); },
        context: "render-skeleton codegen",
        unit_struct: &|_| quote! { touch(node); },
    };
    let body = emitter.item_body(item, schema);

    match item.generics().params.is_empty() {
        true => quote! {
            pub(crate) fn #fn_name(node: &#ty) {
                #body
            }
        },
        false => {
            let mut generics = item.generics().clone();
            for param in &mut generics.params {
                if let GenericParam::Type(type_param) = param {
                    type_param.default = None;
                }
            }
            let (impl_generics, _, where_clause) = generics.split_for_impl();
            quote! {
                pub(crate) fn #fn_name #impl_generics(node: &#ty) #where_clause {
                    #body
                }
            }
        }
    }
}

fn call_target(target: WalkTarget, accessor: TokenStream) -> TokenStream {
    match target {
        WalkTarget::Node(name) => {
            let function = shape_ident(&name);
            quote! { #function(#accessor); }
        }
        WalkTarget::Extension => quote! { render_shape_extension(#accessor); },
    }
}

fn shape_ident(name: &str) -> syn::Ident {
    format_ident!("render_shape_{}", snake_case(name))
}

const FNV_OFFSET_BASIS: u64 = 0xcbf29ce484222325;

fn shape_fingerprint<'a>(items: impl IntoIterator<Item = &'a NodeItem>) -> u64 {
    let mut hash = FNV_OFFSET_BASIS;
    for item in items {
        match item {
            NodeItem::Struct(s) => {
                feed(&mut hash, "struct");
                feed(&mut hash, &s.ident.to_string());
                feed(&mut hash, &s.generics.to_token_stream().to_string());
                feed_fields(&mut hash, &s.fields);
            }
            NodeItem::Enum(e) => {
                feed(&mut hash, "enum");
                feed(&mut hash, &e.ident.to_string());
                feed(&mut hash, &e.generics.to_token_stream().to_string());
                for variant in &e.variants {
                    feed(&mut hash, "variant");
                    feed(&mut hash, &variant.ident.to_string());
                    feed_fields(&mut hash, &variant.fields);
                }
            }
        }
    }
    hash
}

fn feed_fields(hash: &mut u64, fields: &Fields) {
    match fields {
        Fields::Named(fields) => {
            feed(hash, "named");
            for field in &fields.named {
                let ident = field.ident.as_ref().expect("named field has an identifier");
                feed(hash, &ident.to_string());
                feed(hash, &field.ty.to_token_stream().to_string());
            }
        }
        Fields::Unnamed(fields) => {
            feed(hash, "unnamed");
            for field in &fields.unnamed {
                feed(hash, &field.ty.to_token_stream().to_string());
            }
        }
        Fields::Unit => feed(hash, "unit"),
    }
}

fn feed(hash: &mut u64, text: &str) {
    const FNV_PRIME: u64 = 0x00000100000001b3;
    for byte in text.bytes().chain([0]) {
        *hash ^= u64::from(byte);
        *hash = hash.wrapping_mul(FNV_PRIME);
    }
}

fn fingerprint_literal(fingerprint: u64) -> syn::LitInt {
    syn::LitInt::new(&format!("0x{fingerprint:016x}"), Span::call_site())
}
