// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Moderately AI Inc.

//! Emit `Spanned` impls for every node into one formatted source string.
//!
//! Each impl recovers a span with no empty-span holes: struct nodes report
//! `self.meta.span`, metadata-bearing enum nodes report their variant
//! `meta.span`, and the `ObjectName` wrapper unions its identifier parts.
//!
//! An enum variant that has no metadata and no span-bearing child has nothing to
//! report a real span from, so it is rejected at generation time rather than
//! papered over with `Span::SYNTHETIC`: a `Spanned` enum node must be addressable
//! by a true source span (ADR-0002, ADR-0013). A child-less enum node is instead
//! modelled as a metadata-bearing variant (`{ meta: Meta }`), which reports the
//! span the parser captured.

use std::collections::BTreeSet;

use proc_macro2::TokenStream;
use quote::{ToTokens, format_ident, quote};
use syn::{Fields, ItemEnum, ItemStruct, Variant};

use crate::schema::{
    FieldKind, NodeItem, Schema, classify, enum_has_meta, spanned_generics, struct_has_meta,
    type_references_any,
};

/// Prepended verbatim so the `//!` banner survives (token streams carry no
/// line comments) and the regeneration command stays one copy-paste away.
const HEADER: &str = "\
//! @generated by `squonk-sourcegen`; do not edit by hand.
//! Regenerate with `cargo run -p squonk-sourcegen`.

#![allow(clippy::all)]

";

/// Render the full, formatted `generated/spanned.rs` contents.
pub(crate) fn render(schema: &Schema) -> String {
    let impls = schema
        .items
        .iter()
        .filter(|item| schema.is_spanned(&item.name()))
        .map(|item| emit_impl(item, schema));
    let tokens = quote! {
        use crate::ast::*;
        use crate::vocab::Span;

        #(#impls)*
    };
    let file = syn::parse2::<syn::File>(tokens).expect("generated Spanned impls parse as a file");
    format!(
        "{}{HEADER}{}",
        crate::license_header::block(crate::license_header::Comment::Slash),
        prettyplease::unparse(&file)
    )
}

fn emit_impl(item: &NodeItem, schema: &Schema) -> TokenStream {
    match item {
        NodeItem::Struct(s) => emit_struct(s, schema),
        NodeItem::Enum(e) => emit_enum(e, schema),
    }
}

fn emit_struct(s: &ItemStruct, schema: &Schema) -> TokenStream {
    let (impl_generics, ty_generics, where_clause) = s.generics.split_for_impl();
    let name = &s.ident;
    let body = if struct_has_meta(s) {
        quote! { self.meta.span }
    } else {
        // The only spanned struct without `meta`: `ObjectName(pub ThinVec<Ident>)`.
        // Union the spans of its positional fields by index.
        let generics = spanned_generics(&s.generics);
        let exprs = match &s.fields {
            Fields::Unnamed(fields) => fields
                .unnamed
                .iter()
                .enumerate()
                .filter_map(|(index, field)| {
                    classify(&field.ty, &schema.spanned, &generics).map(|kind| {
                        let index = syn::Index::from(index);
                        field_span_expr(quote! { self.#index }, kind)
                    })
                })
                .collect(),
            _ => Vec::new(),
        };
        combine(exprs)
    };
    quote! {
        impl #impl_generics Spanned for #name #ty_generics #where_clause {
            fn span(&self) -> Span {
                #body
            }
        }
    }
}

fn emit_enum(e: &ItemEnum, schema: &Schema) -> TokenStream {
    let (impl_generics, ty_generics, where_clause) = e.generics.split_for_impl();
    let name = &e.ident;
    let generics = spanned_generics(&e.generics);
    let arms = if enum_has_meta(e) {
        e.variants
            .iter()
            .map(|variant| meta_variant_arm(name, variant))
            .collect::<Vec<_>>()
    } else {
        e.variants
            .iter()
            .map(|variant| variant_arm(name, variant, schema, &generics))
            .collect::<Vec<_>>()
    };
    quote! {
        impl #impl_generics Spanned for #name #ty_generics #where_clause {
            fn span(&self) -> Span {
                match self {
                    #(#arms)*
                }
            }
        }
    }
}

/// Build the `match` arm for a metadata-bearing enum variant.
fn meta_variant_arm(enum_name: &syn::Ident, variant: &Variant) -> TokenStream {
    let vname = &variant.ident;
    let Fields::Named(_) = &variant.fields else {
        panic!(
            "spanned codegen: metadata-bearing enum variant `{}::{}` must use \
             named fields including `meta: Meta`",
            enum_name, vname,
        );
    };
    quote! { #enum_name::#vname { meta, .. } => meta.span, }
}

/// Build the `match` arm that computes one variant's span.
fn variant_arm(
    enum_name: &syn::Ident,
    variant: &Variant,
    schema: &Schema,
    generics: &BTreeSet<String>,
) -> TokenStream {
    let vname = &variant.ident;
    match &variant.fields {
        // A truly field-less variant has no child to fold a span from.
        Fields::Unit => reject_spanless_variant(enum_name, vname),
        Fields::Unnamed(fields) => {
            let mut patterns = Vec::new();
            let mut exprs = Vec::new();
            for (index, field) in fields.unnamed.iter().enumerate() {
                match classify(&field.ty, &schema.spanned, generics) {
                    Some(kind) => {
                        let binding = format_ident!("field{}", index);
                        patterns.push(quote! { #binding });
                        exprs.push(field_span_expr(quote! { #binding }, kind));
                    }
                    None => {
                        assert_unspanned(&field.ty, schema, generics);
                        patterns.push(quote! { _ });
                    }
                }
            }
            // No spanned field means the span would fold to `Span::SYNTHETIC` — a
            // hole. Reject instead, exactly as for a unit variant.
            if exprs.is_empty() {
                reject_spanless_variant(enum_name, vname);
            }
            let body = combine(exprs);
            quote! { #enum_name::#vname(#(#patterns),*) => #body, }
        }
        Fields::Named(fields) => {
            let mut bindings = Vec::new();
            let mut exprs = Vec::new();
            let mut omitted = 0_usize;
            for field in &fields.named {
                let ident = field.ident.as_ref().expect("named field has an identifier");
                match classify(&field.ty, &schema.spanned, generics) {
                    Some(kind) => {
                        bindings.push(quote! { #ident });
                        exprs.push(field_span_expr(quote! { #ident }, kind));
                    }
                    None => {
                        assert_unspanned(&field.ty, schema, generics);
                        omitted += 1;
                    }
                }
            }
            // No spanned field (so no binding either) means the span would fold to
            // `Span::SYNTHETIC`. Reject the hole instead of emitting it. A node with
            // only tag/scalar fields must carry `meta: Meta` (`meta_variant_arm`).
            if bindings.is_empty() {
                reject_spanless_variant(enum_name, vname);
            }
            // Bind only spanned fields; `..` absorbs the non-spanned remainder so
            // no binding goes unused under `-D warnings`.
            let pattern = if omitted > 0 {
                quote! { { #(#bindings),* , .. } }
            } else {
                quote! { { #(#bindings),* } }
            };
            let body = combine(exprs);
            quote! { #enum_name::#vname #pattern => #body, }
        }
    }
}

/// Reject a `Spanned` enum variant that cannot report a real source span.
///
/// A variant with no metadata and no span-bearing child has nothing to derive a
/// span from, so the only span it could report is `Span::SYNTHETIC` — exactly the
/// empty-span hole ADR-0013 forbids for parsed nodes. Fail generation instead of
/// emitting the hole: model a child-less enum node as a metadata-bearing variant
/// (`{ meta: Meta }`, ADR-0002) so it reports the parser's span. A node that is
/// intentionally absent from source must opt into synthesis explicitly elsewhere,
/// never by being span-less here.
///
/// Dormant against the current schema — every spanned enum carries `meta` on every
/// variant, so generation routes through [`meta_variant_arm`] — this is the guard
/// that keeps a future field-less variant from silently reintroducing a hole.
fn reject_spanless_variant(enum_name: &syn::Ident, vname: &syn::Ident) -> ! {
    panic!(
        "spanned codegen: enum variant `{enum_name}::{vname}` has no metadata and no \
         span-bearing field, so it cannot report a real source span. Give the variant \
         `meta: Meta` (ADR-0002) so it reports the parser's span instead of a synthetic \
         placeholder (ADR-0013 no-empty-span-holes).",
    );
}

/// Fail generation loudly if a span-fold-skipped field actually references a
/// spanned node — a silent drop would be exactly the empty-span hole ADR-0013
/// forbids. Every field skipped today is a tag/scalar; this guards the future.
fn assert_unspanned(ty: &syn::Type, schema: &Schema, generics: &BTreeSet<String>) {
    assert!(
        !type_references_any(ty, &schema.spanned, generics),
        "spanned codegen: a field of type `{}` references a spanned node but is not \
         folded into the span; extend `classify` in sourcegen/schema.rs",
        ty.to_token_stream(),
    );
}

/// The span expression for one spanned field, given how it is shaped.
fn field_span_expr(accessor: TokenStream, kind: FieldKind) -> TokenStream {
    match kind {
        FieldKind::Direct => quote! { #accessor.span() },
        // `Span::SYNTHETIC` is the union identity, so an empty collection folds to
        // it and contributes nothing — exactly the desired behaviour.
        FieldKind::Fold => quote! {
            #accessor.iter().fold(Span::SYNTHETIC, |acc, item| acc.union(item.span()))
        },
    }
}

/// Fold span expressions into one with `Span::union`; none => `Span::SYNTHETIC`.
///
/// Within [`variant_arm`] the empty case is pre-rejected (see
/// [`reject_spanless_variant`]); the `SYNTHETIC` identity is reached only by the
/// `ObjectName` struct fold, where an empty qualified name legitimately has none.
fn combine(exprs: Vec<TokenStream>) -> TokenStream {
    let mut exprs = exprs.into_iter();
    match exprs.next() {
        None => quote! { Span::SYNTHETIC },
        Some(first) => exprs.fold(first, |acc, expr| quote! { #acc.union(#expr) }),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;
    use syn::parse_quote;

    /// A node-free `Schema`: `variant_arm`'s field-shape arms inspect only the
    /// variant's own fields, so the spanned/reachable sets are irrelevant here.
    fn empty_schema() -> Schema {
        Schema {
            items: Vec::new(),
            families: BTreeMap::new(),
            item_names: BTreeSet::new(),
            spanned: BTreeSet::new(),
            reachable: BTreeSet::new(),
        }
    }

    /// A field-less (`Fields::Unit`) variant has no child to derive a span from, so
    /// the generator must refuse it rather than emit a `Span::SYNTHETIC` hole.
    #[test]
    #[should_panic(expected = "cannot report a real source span")]
    fn rejects_field_less_spanned_enum_variant() {
        let item: ItemEnum = parse_quote! {
            enum Demo {
                Bare,
            }
        };
        let _ = variant_arm(
            &item.ident,
            &item.variants[0],
            &empty_schema(),
            &BTreeSet::new(),
        );
    }

    /// The same hole one variant up: fields exist but none is span-bearing, so the
    /// span would fold to `Span::SYNTHETIC`. Rejected for the same reason.
    #[test]
    #[should_panic(expected = "cannot report a real source span")]
    fn rejects_variant_whose_fields_are_all_non_spanned() {
        let item: ItemEnum = parse_quote! {
            enum Demo {
                Flag(bool),
            }
        };
        let _ = variant_arm(
            &item.ident,
            &item.variants[0],
            &empty_schema(),
            &BTreeSet::new(),
        );
    }
}
