// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Moderately AI Inc.

//! Emit binding declarations and metadata for the serde JSON AST.

use std::collections::BTreeSet;

use syn::{Fields, GenericArgument, Ident, ItemEnum, ItemStruct, PathArguments, Type, TypePath};

use crate::schema::{NodeItem, Schema, extension_generics};

const HEADER: &str = "\
// @generated by the `squonk-sourcegen` xtask -- do not edit by hand.
//
// TypeScript declarations for the serde JSON AST emitted by the WASM bindings.
// Regenerate after changing any Rust AST node:
// `cargo run -p squonk-sourcegen`.

";

const METADATA_HEADER: &str = "\
// @generated by the `squonk-sourcegen` xtask -- do not edit by hand.
//
// Runtime metadata for the serde JSON AST emitted by the bindings.
// Regenerate after changing any Rust AST node:
// `cargo run -p squonk-sourcegen`.

";

const PY_METADATA_HEADER: &str = "\
# @generated by the `squonk-sourcegen` xtask -- do not edit by hand.
#
# Runtime metadata for the serde JSON AST emitted by the bindings.
# Regenerate after changing any Rust AST node:
# `cargo run -p squonk-sourcegen`.

";

pub(crate) fn render(schema: &Schema) -> String {
    let mut out = crate::license_header::block(crate::license_header::Comment::Slash);
    out.push_str(HEADER);
    out.push_str("export type Symbol = number;\n");
    out.push_str("export type NodeId = number;\n\n");
    out.push_str("export interface Span {\n  start: number;\n  end: number;\n}\n\n");
    out.push_str("export interface Meta {\n  span: Span;\n  node_id: NodeId;\n}\n\n");

    for item in schema
        .items
        .iter()
        .filter(|item| schema.is_reachable(&item.name()))
    {
        match item {
            NodeItem::Struct(s) => render_struct(schema, s, &mut out),
            NodeItem::Enum(e) => render_enum(schema, e, &mut out),
        }
        out.push('\n');
    }

    let nodes = schema
        .items
        .iter()
        .filter(|item| schema.is_reachable(&item.name()))
        .map(NodeItem::name)
        .filter(|name| name != "NoExt")
        .collect::<Vec<_>>();
    out.push_str("export type AstNode =\n");
    for (index, name) in nodes.iter().enumerate() {
        let suffix = if index + 1 == nodes.len() {
            ";\n"
        } else {
            "\n"
        };
        out.push_str(&format!("  | {name}{suffix}"));
    }

    out
}

fn render_struct(schema: &Schema, s: &ItemStruct, out: &mut String) {
    let generics = extension_generics(&s.generics);
    match &s.fields {
        Fields::Named(fields) => {
            out.push_str(&format!("export interface {} {{\n", s.ident));
            for field in &fields.named {
                let name = field.ident.as_ref().expect("named field has an identifier");
                let ty = ts_type(schema, &field.ty, &generics);
                out.push_str(&format!("  {}: {ty};\n", serde_name(name)));
            }
            out.push_str("}\n");
        }
        Fields::Unnamed(fields) => {
            let types = fields
                .unnamed
                .iter()
                .map(|field| ts_type(schema, &field.ty, &generics))
                .collect::<Vec<_>>();
            let ty = if types.len() == 1 {
                types[0].clone()
            } else {
                format!("[{}]", types.join(", "))
            };
            out.push_str(&format!("export type {} = {ty};\n", s.ident));
        }
        Fields::Unit => {
            out.push_str(&format!("export type {} = {{}};\n", s.ident));
        }
    }
}

fn render_enum(schema: &Schema, e: &ItemEnum, out: &mut String) {
    if e.ident == "NoExt" || e.variants.is_empty() {
        out.push_str(&format!("export type {} = never;\n", e.ident));
        return;
    }

    let generics = extension_generics(&e.generics);
    out.push_str(&format!("export type {} =\n", e.ident));
    for (index, variant) in e.variants.iter().enumerate() {
        let variant_ty = match &variant.fields {
            Fields::Unit => format!("{:?}", variant.ident.to_string()),
            Fields::Named(fields) => {
                let mut body = String::from("{ ");
                for field in &fields.named {
                    let name = field
                        .ident
                        .as_ref()
                        .expect("named variant field has an identifier");
                    let ty = ts_type(schema, &field.ty, &generics);
                    body.push_str(&format!("{}: {ty}; ", serde_name(name)));
                }
                body.push('}');
                format!("{{ {}: {body} }}", variant.ident)
            }
            Fields::Unnamed(fields) => {
                let types = fields
                    .unnamed
                    .iter()
                    .map(|field| ts_type(schema, &field.ty, &generics))
                    .collect::<Vec<_>>();
                let payload = if types.len() == 1 {
                    types[0].clone()
                } else {
                    format!("[{}]", types.join(", "))
                };
                format!("{{ {}: {payload} }}", variant.ident)
            }
        };
        let suffix = if index + 1 == e.variants.len() {
            ";\n"
        } else {
            "\n"
        };
        out.push_str(&format!("  | {variant_ty}{suffix}"));
    }
}

pub(crate) fn render_metadata_js(schema: &Schema) -> String {
    let entries = field_metadata(schema);
    let mut out = crate::license_header::block(crate::license_header::Comment::Slash);
    out.push_str(METADATA_HEADER);
    out.push_str("export const AST_FIELD_TYPES = Object.freeze({\n");
    for (type_name, fields) in entries {
        out.push_str(&format!("  {}: Object.freeze({{\n", js_string(&type_name)));
        for (field_name, field_type) in fields {
            out.push_str(&format!(
                "    {}: {},\n",
                js_string(&field_name),
                js_string(&field_type)
            ));
        }
        out.push_str("  }),\n");
    }
    out.push_str("});\n");
    out
}

pub(crate) fn render_metadata_py(schema: &Schema) -> String {
    let entries = field_metadata(schema);
    let mut out = crate::license_header::block(crate::license_header::Comment::Hash);
    out.push_str(PY_METADATA_HEADER);
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("AST_FIELD_TYPES: dict[str, dict[str, str]] = {\n");
    for (type_name, fields) in entries {
        out.push_str(&format!("    {}: {{\n", py_string(&type_name)));
        for (field_name, field_type) in fields {
            out.push_str(&format!(
                "        {}: {},\n",
                py_string(&field_name),
                py_string(&field_type)
            ));
        }
        out.push_str("    },\n");
    }
    out.push_str("}\n");
    out
}

fn field_metadata(schema: &Schema) -> Vec<(String, Vec<(String, String)>)> {
    let mut out = Vec::new();
    for item in schema
        .items
        .iter()
        .filter(|item| schema.is_reachable(&item.name()))
    {
        match item {
            NodeItem::Struct(s) => {
                let generics = extension_generics(&s.generics);
                if let Fields::Named(fields) = &s.fields {
                    let field_types = fields
                        .named
                        .iter()
                        .filter_map(|field| {
                            let name = field.ident.as_ref().expect("named field has an identifier");
                            binding_type(schema, &field.ty, &generics)
                                .map(|ty| (serde_name(name), ty))
                        })
                        .collect::<Vec<_>>();
                    if !field_types.is_empty() {
                        out.push((s.ident.to_string(), field_types));
                    }
                }
            }
            NodeItem::Enum(e) => {
                let generics = extension_generics(&e.generics);
                for variant in &e.variants {
                    if let Fields::Named(fields) = &variant.fields {
                        let field_types = fields
                            .named
                            .iter()
                            .filter_map(|field| {
                                let name =
                                    field.ident.as_ref().expect("named field has an identifier");
                                binding_type(schema, &field.ty, &generics)
                                    .map(|ty| (serde_name(name), ty))
                            })
                            .collect::<Vec<_>>();
                        if !field_types.is_empty() {
                            out.push((format!("{}.{}", e.ident, variant.ident), field_types));
                        }
                    }
                }
            }
        }
    }
    out
}

fn binding_type(schema: &Schema, ty: &Type, generics: &BTreeSet<String>) -> Option<String> {
    match ty {
        Type::Path(TypePath { qself: None, path }) => {
            let segment = path
                .segments
                .last()
                .expect("path type has at least one segment");
            let name = segment.ident.to_string();
            match name.as_str() {
                "Box" | "Option" => binding_type(schema, single_type_arg(segment), generics),
                "Vec" | "ThinVec" => {
                    let inner = binding_type(schema, single_type_arg(segment), generics)?;
                    Some(format!("{inner}[]"))
                }
                other if generics.contains(other) => Some("NoExt".to_owned()),
                other if schema.is_ast_item(other) => Some(other.to_owned()),
                _ => None,
            }
        }
        Type::Reference(reference) => binding_type(schema, &reference.elem, generics),
        Type::Array(array) => {
            binding_type(schema, &array.elem, generics).map(|inner| format!("{inner}[]"))
        }
        Type::Slice(slice) => {
            binding_type(schema, &slice.elem, generics).map(|inner| format!("{inner}[]"))
        }
        Type::Group(group) => binding_type(schema, &group.elem, generics),
        Type::Paren(paren) => binding_type(schema, &paren.elem, generics),
        _ => None,
    }
}

fn ts_type(schema: &Schema, ty: &Type, generics: &BTreeSet<String>) -> String {
    match ty {
        Type::Path(TypePath { qself: None, path }) => {
            let segment = path
                .segments
                .last()
                .expect("path type has at least one segment");
            let name = segment.ident.to_string();
            match name.as_str() {
                "Box" => ts_type(schema, single_type_arg(segment), generics),
                "Option" => format!(
                    "{} | null",
                    ts_type(schema, single_type_arg(segment), generics)
                ),
                "Vec" | "ThinVec" => {
                    format!(
                        "{}[]",
                        parenthesize_array_element(ts_type(
                            schema,
                            single_type_arg(segment),
                            generics
                        ))
                    )
                }
                "bool" => "boolean".to_owned(),
                "u8" | "u16" | "u32" | "u64" | "usize" | "i8" | "i16" | "i32" | "i64" | "isize" => {
                    "number".to_owned()
                }
                "String" | "str" => "string".to_owned(),
                "Symbol" | "FoldedSymbol" | "NodeId" => "number".to_owned(),
                "Span" | "Meta" => name,
                other if generics.contains(other) => "NoExt".to_owned(),
                other if schema.is_reachable(other) || schema.is_ast_item(other) => {
                    other.to_owned()
                }
                other => panic!("cannot map Rust AST type `{other}` to TypeScript"),
            }
        }
        Type::Tuple(tuple) => {
            if tuple.elems.is_empty() {
                "[]".to_owned()
            } else {
                let elems = tuple
                    .elems
                    .iter()
                    .map(|elem| ts_type(schema, elem, generics))
                    .collect::<Vec<_>>();
                format!("[{}]", elems.join(", "))
            }
        }
        Type::Reference(reference) => ts_type(schema, &reference.elem, generics),
        Type::Array(array) => {
            format!(
                "{}[]",
                parenthesize_array_element(ts_type(schema, &array.elem, generics))
            )
        }
        Type::Slice(slice) => {
            format!(
                "{}[]",
                parenthesize_array_element(ts_type(schema, &slice.elem, generics))
            )
        }
        Type::Group(group) => ts_type(schema, &group.elem, generics),
        Type::Paren(paren) => ts_type(schema, &paren.elem, generics),
        _ => panic!("cannot map unsupported Rust AST type shape to TypeScript"),
    }
}

fn parenthesize_array_element(ty: String) -> String {
    if ty.contains(" | ") {
        format!("({ty})")
    } else {
        ty
    }
}

fn serde_name(ident: &Ident) -> String {
    let name = ident.to_string();
    name.strip_prefix("r#").unwrap_or(&name).to_owned()
}

fn js_string(value: &str) -> String {
    format!("{value:?}")
}

fn py_string(value: &str) -> String {
    format!("{value:?}")
}

fn single_type_arg(segment: &syn::PathSegment) -> &Type {
    let PathArguments::AngleBracketed(args) = &segment.arguments else {
        panic!("{} must carry one type argument", segment.ident);
    };
    args.args
        .iter()
        .find_map(|arg| match arg {
            GenericArgument::Type(ty) => Some(ty),
            _ => None,
        })
        .unwrap_or_else(|| panic!("{} must carry one type argument", segment.ident))
}
