// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Moderately AI Inc.

//! Emit generated `Visit` / `VisitMut` traits and AST walks.

use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use crate::descent::{DescentEmitter, Mutability, item_ty};
use crate::schema::{NodeItem, Schema, WalkTarget, snake_case};

const HEADER: &str = "\
//! @generated by `squonk-sourcegen`; do not edit by hand.
//! Regenerate with `cargo run -p squonk-sourcegen`.

#![allow(clippy::all)]

";

pub(crate) fn render(schema: &Schema) -> String {
    let visit_methods = schema
        .items
        .iter()
        .filter(|item| schema.is_reachable(&item.name()))
        .map(emit_visit_method);
    let visit_walks = schema
        .items
        .iter()
        .filter(|item| schema.is_reachable(&item.name()))
        .map(|item| emit_walk(item, schema, Mutability::Shared));
    let visit_mut_methods = schema
        .items
        .iter()
        .filter(|item| schema.is_reachable(&item.name()))
        .map(emit_visit_mut_method);
    let visit_mut_walks = schema
        .items
        .iter()
        .filter(|item| schema.is_reachable(&item.name()))
        .map(|item| emit_walk(item, schema, Mutability::Mutable));

    let tokens = quote! {
        use crate::ast::*;

        /// Read-only depth-first traversal of every node in an SQL AST.
        ///
        /// Override the node methods of interest; each default implementation
        /// delegates to its corresponding `walk_*` function.
        pub trait Visit<'ast, X: Extension = NoExt> {
            #(#visit_methods)*

            /// Visit an open extension node.
            fn visit_extension(&mut self, node: &'ast X) {
                let _ = node;
            }
        }

        #(#visit_walks)*

        /// Mutable depth-first traversal of every node in an SQL AST.
        ///
        /// Override the node methods of interest; each default implementation
        /// delegates to its corresponding `walk_*_mut` function.
        pub trait VisitMut<X: Extension = NoExt> {
            #(#visit_mut_methods)*

            /// Visit a mutable open extension node.
            fn visit_extension_mut(&mut self, node: &mut X) {
                let _ = node;
            }
        }

        #(#visit_mut_walks)*
    };
    let file = syn::parse2::<syn::File>(tokens).expect("generated Visit impls parse as a file");
    format!(
        "{}{HEADER}{}",
        crate::license_header::block(crate::license_header::Comment::Slash),
        prettyplease::unparse(&file)
    )
}

fn emit_visit_method(item: &NodeItem) -> TokenStream {
    let name = item.name();
    let method = method_ident("visit", &item.name(), Mutability::Shared);
    let walk = walk_ident(&item.name(), Mutability::Shared);
    let ty = item_ty(item);
    let doc = format!("Visit a [`{name}`] node and recursively walk its children.");
    quote! {
        #[doc = #doc]
        fn #method(&mut self, node: &'ast #ty) {
            #walk(self, node);
        }
    }
}

fn emit_visit_mut_method(item: &NodeItem) -> TokenStream {
    let name = item.name();
    let method = method_ident("visit", &item.name(), Mutability::Mutable);
    let walk = walk_ident(&item.name(), Mutability::Mutable);
    let ty = item_ty(item);
    let doc = format!("Visit a mutable [`{name}`] node and recursively walk its children.");
    quote! {
        #[doc = #doc]
        fn #method(&mut self, node: &mut #ty) {
            #walk(self, node);
        }
    }
}

fn emit_walk(item: &NodeItem, schema: &Schema, mutability: Mutability) -> TokenStream {
    let name = item.name();
    let walk = walk_ident(&item.name(), mutability);
    let ty = item_ty(item);
    let emitter = DescentEmitter {
        mutability,
        leaf: &|target, accessor| call_target(target, accessor, mutability),
        // A non-node field is named so the destructuring binding is used.
        fallback: &|accessor| quote! { let _ = #accessor; },
        context: "visitor codegen",
        // A unit struct still rebinds the node so the walk signature is exercised.
        unit_struct: &|name| quote! { let #name = node; },
    };
    let body = emitter.item_body(item, schema);

    match mutability {
        Mutability::Shared => {
            let doc = format!("Walk the immediate children of a [`{name}`] node.");
            quote! {
            #[doc = #doc]
            pub fn #walk<'ast, V, X>(visitor: &mut V, node: &'ast #ty)
            where
                V: Visit<'ast, X> + ?Sized,
                X: Extension,
            {
                let _ = &mut *visitor;
                #body
            }
            }
        }
        Mutability::Mutable => {
            let doc = format!("Walk the immediate children of a mutable [`{name}`] node.");
            quote! {
            #[doc = #doc]
            pub fn #walk<V, X>(visitor: &mut V, node: &mut #ty)
            where
                V: VisitMut<X> + ?Sized,
                X: Extension,
            {
                let _ = &mut *visitor;
                #body
            }
            }
        }
    }
}

fn call_target(target: WalkTarget, accessor: TokenStream, mutability: Mutability) -> TokenStream {
    match target {
        WalkTarget::Node(name) => {
            let method = method_ident("visit", &name, mutability);
            quote! { visitor.#method(#accessor); }
        }
        WalkTarget::Extension => {
            let method = match mutability {
                Mutability::Shared => format_ident!("visit_extension"),
                Mutability::Mutable => format_ident!("visit_extension_mut"),
            };
            quote! { visitor.#method(#accessor); }
        }
    }
}

fn method_ident(prefix: &str, name: &str, mutability: Mutability) -> syn::Ident {
    let suffix = snake_case(name);
    match mutability {
        Mutability::Shared => format_ident!("{prefix}_{suffix}"),
        Mutability::Mutable => format_ident!("{prefix}_{suffix}_mut"),
    }
}

fn walk_ident(name: &str, mutability: Mutability) -> syn::Ident {
    method_ident("walk", name, mutability)
}
