// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Moderately AI Inc.

export type * from "./runtime.js";
export type * from "../js/ast.generated.js";
export { SqlParseError, Document, RecoveredDocument, Node, Ident, ObjectName, Diagnostic } from "./runtime.js";
export declare const isDialectName: (value: string) => value is import("./runtime.js").ValidatedDialectName<"ansi">, assertDialectName: (value: string) => asserts value is import("./runtime.js").ValidatedDialectName<"ansi">, canonicalDialectName: (value: string) => "ansi" | null, parse: <const TDialect extends import("./runtime.js").DialectName<"ansi"> = "ansi">(sql: string, options?: import("./runtime.js").ParseConfig<"ansi", TDialect> | undefined) => import("./runtime.js").Document<import("./runtime.js").ParseResult<import("./runtime.js").CanonicalDialect<TDialect>>, import("./runtime.js").CanonicalDialect<TDialect>, "ansi">, parseJson: <const TDialect extends import("./runtime.js").DialectName<"ansi"> = "ansi">(sql: string, options?: import("./runtime.js").ParseConfig<"ansi", TDialect> | undefined) => import("./runtime.js").ParseResult<import("./runtime.js").CanonicalDialect<TDialect>>, parseWithLimit: <const TDialect extends import("./runtime.js").DialectName<"ansi">>(sql: string, dialect: TDialect, limit: number) => import("./runtime.js").Document<import("./runtime.js").ParseResult<import("./runtime.js").CanonicalDialect<TDialect>>, import("./runtime.js").CanonicalDialect<TDialect>, "ansi">, parseRecovering: <const TDialect extends import("./runtime.js").DialectName<"ansi"> = "ansi">(sql: string, options?: import("./runtime.js").ParseConfig<"ansi", TDialect> | undefined) => import("./runtime.js").RecoveredDocument<import("./runtime.js").RecoveringParseResult<import("./runtime.js").CanonicalDialect<TDialect>>, import("./runtime.js").CanonicalDialect<TDialect>, "ansi">, parseRecoveringJson: <const TDialect extends import("./runtime.js").DialectName<"ansi"> = "ansi">(sql: string, options?: import("./runtime.js").ParseConfig<"ansi", TDialect> | undefined) => import("./runtime.js").RecoveringParseResult<import("./runtime.js").CanonicalDialect<TDialect>>, supportedDialects: () => import("./runtime.js").DialectInfo<"ansi">[], tokenize: <const TDialect extends import("./runtime.js").DialectName<"ansi"> = "ansi">(sql: string, options?: {
    dialect?: TDialect | undefined;
    includeTrivia?: boolean;
} | undefined) => import("./runtime.js").TokenizeResult<import("./runtime.js").CanonicalDialect<TDialect>>, render: <const TTargetDialect extends import("./runtime.js").DialectName<"ansi"> = import("./runtime.js").DialectName<"ansi">>(sqlOrDocument: string | import("./runtime.js").Document<import("./runtime.js").ParseResult<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient">, "ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient", "ansi">, options?: import("./runtime.js").RenderOptions<"ansi", TTargetDialect> | undefined) => string, redact: <const TTargetDialect extends import("./runtime.js").DialectName<"ansi"> = import("./runtime.js").DialectName<"ansi">>(sqlOrDocument: string | import("./runtime.js").Document<import("./runtime.js").ParseResult<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient">, "ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient", "ansi">, options?: Omit<import("./runtime.js").RenderOptions<"ansi", TTargetDialect>, "mode"> | undefined) => string, format: <const TDialect extends import("./runtime.js").DialectName<"ansi"> = "ansi">(sql: string, options?: import("./runtime.js").FormatOptions<"ansi", TDialect> | undefined) => string, transpile: <const TSourceDialect extends import("./runtime.js").DialectName<"ansi"> = "ansi", const TTargetDialect extends import("./runtime.js").DialectName<"ansi"> = "ansi">(sql: string, options?: import("./runtime.js").TranspileOptions<"ansi", TSourceDialect, TTargetDialect> | undefined) => string, version: () => string, schemaVersion: () => number, runtimeInfo: () => import("./runtime.js").RuntimeInfo;
