// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Moderately AI Inc.

export type * from "./runtime.js";
export type * from "../js/ast.generated.js";
export { Diagnostic, Document, Ident, Node, ObjectName, RecoveredDocument, SqlParseError } from "./runtime.js";
/** Return true when a dynamic string is a dialect accepted by this entrypoint. */
export declare const isDialectName: (value: string) => value is import("./runtime.js").ValidatedDialectName<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient">;
/** Throw `SqlParseError` unless a dynamic string is a dialect accepted by this entrypoint. */
export declare const assertDialectName: (value: string) => asserts value is import("./runtime.js").ValidatedDialectName<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient">;
/** Canonicalize a dynamic dialect string for this entrypoint, or return null. */
export declare const canonicalDialectName: (value: string) => "ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient" | null;
/** Parse SQL and throw on the first parser diagnostic. */
export declare const parse: <const TDialect extends import("./runtime.js").DialectName<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient"> = "ansi">(sql: string, options?: import("./runtime.js").ParseOptions<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient", TDialect> | undefined) => import("./runtime.js").Document<import("./runtime.js").ParseResult<import("./runtime.js").CanonicalDialect<TDialect>>, import("./runtime.js").CanonicalDialect<TDialect>, "ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient">;
/** Parse SQL and return the raw JSON payload. */
export declare const parseJson: <const TDialect extends import("./runtime.js").DialectName<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient"> = "ansi">(sql: string, options?: import("./runtime.js").ParseOptions<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient", TDialect> | undefined) => import("./runtime.js").ParseResult<import("./runtime.js").CanonicalDialect<TDialect>>;
/** Parse SQL with an explicit recursion-depth limit. */
export declare const parseWithLimit: <const TDialect extends import("./runtime.js").DialectName<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient">>(sql: string, dialect: TDialect, limit: number) => import("./runtime.js").Document<import("./runtime.js").ParseResult<import("./runtime.js").CanonicalDialect<TDialect>>, import("./runtime.js").CanonicalDialect<TDialect>, "ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient">;
/** Parse SQL while recovering statement-level syntax errors. */
export declare const parseRecovering: <const TDialect extends import("./runtime.js").DialectName<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient"> = "ansi">(sql: string, options?: import("./runtime.js").ParseOptions<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient", TDialect> | undefined) => import("./runtime.js").RecoveredDocument<import("./runtime.js").RecoveringParseResult<import("./runtime.js").CanonicalDialect<TDialect>>, import("./runtime.js").CanonicalDialect<TDialect>, "ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient">;
/** Recovering parse that returns the raw JSON payload. */
export declare const parseRecoveringJson: <const TDialect extends import("./runtime.js").DialectName<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient"> = "ansi">(sql: string, options?: import("./runtime.js").ParseOptions<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient", TDialect> | undefined) => import("./runtime.js").RecoveringParseResult<import("./runtime.js").CanonicalDialect<TDialect>>;
/** Return dialect metadata compiled into this entrypoint. */
export declare const supportedDialects: () => import("./runtime.js").DialectInfo<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient">[];
/** Tokenize SQL under a supported dialect. */
export declare const tokenize: <const TDialect extends import("./runtime.js").DialectName<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient"> = "ansi">(sql: string, options?: {
    dialect?: TDialect | undefined;
    includeTrivia?: boolean;
} | undefined) => import("./runtime.js").TokenizeResult<import("./runtime.js").CanonicalDialect<TDialect>>;
/** Render a SQL string or parsed document. */
export declare const render: <const TTargetDialect extends import("./runtime.js").DialectName<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient"> = import("./runtime.js").DialectName<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient">>(sqlOrDocument: string | import("./runtime.js").Document<import("./runtime.js").ParseResult<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient">, "ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient", "ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient">, options?: import("./runtime.js").RenderOptions<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient", TTargetDialect> | undefined) => string;
/** Render a SQL string or parsed document in redaction mode. */
export declare const redact: <const TTargetDialect extends import("./runtime.js").DialectName<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient"> = import("./runtime.js").DialectName<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient">>(sqlOrDocument: string | import("./runtime.js").Document<import("./runtime.js").ParseResult<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient">, "ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient", "ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient">, options?: Omit<import("./runtime.js").RenderOptions<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient", TTargetDialect>, "mode"> | undefined) => string;
/** Pretty-print SQL. */
export declare const format: <const TDialect extends import("./runtime.js").DialectName<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient"> = "ansi">(sql: string, options?: import("./runtime.js").FormatOptions<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient", TDialect> | undefined) => string;
/** Parse SQL under one dialect and render it under another. */
export declare const transpile: <const TSourceDialect extends import("./runtime.js").DialectName<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient"> = "ansi", const TTargetDialect extends import("./runtime.js").DialectName<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient"> = "ansi">(sql: string, options?: import("./runtime.js").TranspileOptions<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient", TSourceDialect, TTargetDialect> | undefined) => string;
/** Return the crate/package version string. */
export declare const version: () => string;
/** Return the serialized AST wire-schema version. */
export declare const schemaVersion: () => number;
