// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Moderately AI Inc.

export type * from "./runtime.js";
export type * from "../js/ast.generated.js";
export { SqlParseError, Document, RecoveredDocument, Node, Ident, ObjectName, Diagnostic } from "./runtime.js";
export declare const isDialectName: (value: string) => value is import("./runtime.js").ValidatedDialectName<"ansi" | "postgres">, assertDialectName: (value: string) => asserts value is import("./runtime.js").ValidatedDialectName<"ansi" | "postgres">, canonicalDialectName: (value: string) => "ansi" | "postgres" | null, parse: <const TDialect extends import("./runtime.js").DialectName<"ansi" | "postgres"> = "postgres">(sql: string, options?: import("./runtime.js").ParseConfig<"ansi" | "postgres", TDialect> | undefined) => import("./runtime.js").Document<import("./runtime.js").ParseResult<import("./runtime.js").CanonicalDialect<TDialect>>, import("./runtime.js").CanonicalDialect<TDialect>, "ansi" | "postgres">, parseJson: <const TDialect extends import("./runtime.js").DialectName<"ansi" | "postgres"> = "postgres">(sql: string, options?: import("./runtime.js").ParseConfig<"ansi" | "postgres", TDialect> | undefined) => import("./runtime.js").ParseResult<import("./runtime.js").CanonicalDialect<TDialect>>, parseWithLimit: <const TDialect extends import("./runtime.js").DialectName<"ansi" | "postgres">>(sql: string, dialect: TDialect, limit: number) => import("./runtime.js").Document<import("./runtime.js").ParseResult<import("./runtime.js").CanonicalDialect<TDialect>>, import("./runtime.js").CanonicalDialect<TDialect>, "ansi" | "postgres">, parseRecovering: <const TDialect extends import("./runtime.js").DialectName<"ansi" | "postgres"> = "postgres">(sql: string, options?: import("./runtime.js").ParseConfig<"ansi" | "postgres", TDialect> | undefined) => import("./runtime.js").RecoveredDocument<import("./runtime.js").RecoveringParseResult<import("./runtime.js").CanonicalDialect<TDialect>>, import("./runtime.js").CanonicalDialect<TDialect>, "ansi" | "postgres">, parseRecoveringJson: <const TDialect extends import("./runtime.js").DialectName<"ansi" | "postgres"> = "postgres">(sql: string, options?: import("./runtime.js").ParseConfig<"ansi" | "postgres", TDialect> | undefined) => import("./runtime.js").RecoveringParseResult<import("./runtime.js").CanonicalDialect<TDialect>>, supportedDialects: () => import("./runtime.js").DialectInfo<"ansi" | "postgres">[], tokenize: <const TDialect extends import("./runtime.js").DialectName<"ansi" | "postgres"> = "postgres">(sql: string, options?: {
    dialect?: TDialect | undefined;
    includeTrivia?: boolean;
} | undefined) => import("./runtime.js").TokenizeResult<import("./runtime.js").CanonicalDialect<TDialect>>, render: <const TTargetDialect extends import("./runtime.js").DialectName<"ansi" | "postgres"> = import("./runtime.js").DialectName<"ansi" | "postgres">>(sqlOrDocument: string | import("./runtime.js").Document<import("./runtime.js").ParseResult<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient">, "ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient", "ansi" | "postgres">, options?: import("./runtime.js").RenderOptions<"ansi" | "postgres", TTargetDialect> | undefined) => string, redact: <const TTargetDialect extends import("./runtime.js").DialectName<"ansi" | "postgres"> = import("./runtime.js").DialectName<"ansi" | "postgres">>(sqlOrDocument: string | import("./runtime.js").Document<import("./runtime.js").ParseResult<"ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient">, "ansi" | "postgres" | "mysql" | "sqlite" | "duckdb" | "bigquery" | "hive" | "clickhouse" | "databricks" | "mssql" | "snowflake" | "redshift" | "lenient", "ansi" | "postgres">, options?: Omit<import("./runtime.js").RenderOptions<"ansi" | "postgres", TTargetDialect>, "mode"> | undefined) => string, format: <const TDialect extends import("./runtime.js").DialectName<"ansi" | "postgres"> = "postgres">(sql: string, options?: import("./runtime.js").FormatOptions<"ansi" | "postgres", TDialect> | undefined) => string, transpile: <const TSourceDialect extends import("./runtime.js").DialectName<"ansi" | "postgres"> = "postgres", const TTargetDialect extends import("./runtime.js").DialectName<"ansi" | "postgres"> = "postgres">(sql: string, options?: import("./runtime.js").TranspileOptions<"ansi" | "postgres", TSourceDialect, TTargetDialect> | undefined) => string, version: () => string, schemaVersion: () => number, runtimeInfo: () => import("./runtime.js").RuntimeInfo;
