# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Moderately AI Inc.

# @generated by the `squonk-sourcegen` xtask -- do not edit by hand.
#
# Runtime metadata for the serde JSON AST emitted by the bindings.
# Regenerate after changing any Rust AST node:
# `cargo run -p squonk-sourcegen`.

from __future__ import annotations

AST_FIELD_TYPES: dict[str, dict[str, str]] = {
    "SessionStatement.Set": {
        "scope": "SetScope",
        "name": "ObjectName",
        "assignment": "SetAssignment",
        "value": "SetValue",
    },
    "SessionStatement.SetTimeZone": {
        "scope": "SetScope",
        "value": "SpecialSetValue",
    },
    "SessionStatement.SetRole": {
        "scope": "SetScope",
        "role": "SpecialSetValue",
    },
    "SessionStatement.SetSessionAuthorization": {
        "scope": "SetScope",
        "user": "SpecialSetValue",
    },
    "SessionStatement.SetConstraints": {
        "constraints": "ConstraintsTarget",
        "check_time": "ConstraintCheckTime",
    },
    "SessionStatement.SetNames": {
        "value": "SetNamesValue",
    },
    "SessionStatement.SetSessionCharacteristics": {
        "modes": "TransactionMode[]",
    },
    "SessionStatement.Reset": {
        "scope": "SetScope",
        "target": "ConfigParameter",
    },
    "SessionStatement.Show": {
        "target": "ConfigParameter",
    },
    "SessionStatement.SetVariables": {
        "assignments": "SetVariableAssignment[]",
    },
    "SessionStatement.SetCharacterSet": {
        "keyword": "CharacterSetKeyword",
        "value": "SetCharacterSetValue",
    },
    "SessionStatement.SetResourceGroup": {
        "name": "Ident",
        "thread_ids": "Literal[]",
    },
    "SetVariableAssignment.SystemVariable": {
        "scope": "SystemVariableScope",
        "name": "ObjectName",
        "assignment": "SetAssignment",
        "value": "SetVariableValue",
    },
    "SetVariableAssignment.UserVariable": {
        "name": "Ident",
        "assignment": "SetAssignment",
        "value": "Expr",
    },
    "SetVariableValue.Keyword": {
        "keyword": "SetVariableKeyword",
    },
    "SetVariableValue.Expr": {
        "expr": "Expr",
    },
    "SetCharacterSetValue.Charset": {
        "charset": "SetParameterValue",
    },
    "SetValue.Values": {
        "values": "SetParameterValue[]",
    },
    "SetParameterValue.Literal": {
        "literal": "Literal",
    },
    "SetParameterValue.Name": {
        "name": "Ident",
    },
    "SetParameterValue.List": {
        "values": "SetParameterValue[]",
    },
    "SpecialSetValue.Value": {
        "value": "SetParameterValue",
    },
    "ConstraintsTarget.Names": {
        "names": "ObjectName[]",
    },
    "SetNamesValue.Charset": {
        "charset": "SetParameterValue",
        "collation": "Ident",
    },
    "ConfigParameter.Named": {
        "name": "ObjectName",
    },
    "AlterSystem": {
        "action": "AlterSystemAction",
    },
    "AlterSystemAction.Set": {
        "name": "ObjectName",
        "assignment": "SetAssignment",
        "value": "SetValue",
    },
    "AlterSystemAction.Reset": {
        "target": "ConfigParameter",
    },
    "AccessControlStatement.AlterRoleRename": {
        "name": "Ident",
        "new_name": "Ident",
    },
    "AccessControlStatement.Grant": {
        "privileges": "Privileges",
        "object": "GrantObject",
        "grantees": "Grantee[]",
        "granted_by": "RoleSpec",
    },
    "AccessControlStatement.Revoke": {
        "privileges": "Privileges",
        "object": "GrantObject",
        "grantees": "Grantee[]",
        "granted_by": "RoleSpec",
        "behavior": "DropBehavior",
    },
    "AccessControlStatement.GrantRole": {
        "roles": "Ident[]",
        "grantees": "Grantee[]",
        "granted_by": "RoleSpec",
    },
    "AccessControlStatement.RevokeRole": {
        "roles": "Ident[]",
        "grantees": "Grantee[]",
        "granted_by": "RoleSpec",
        "behavior": "DropBehavior",
    },
    "AccessControlStatement.AccountGrantPrivilege": {
        "privileges": "Privileges",
        "object": "PrivilegeLevelObject",
        "grantees": "AccountName[]",
        "grant_as": "GrantAs",
    },
    "AccessControlStatement.AccountGrantProxy": {
        "proxy": "AccountName",
        "grantees": "AccountName[]",
    },
    "AccessControlStatement.AccountGrantRole": {
        "roles": "AccountName[]",
        "grantees": "AccountName[]",
    },
    "AccessControlStatement.AccountRevokePrivilege": {
        "privileges": "Privileges",
        "object": "PrivilegeLevelObject",
        "grantees": "AccountName[]",
    },
    "AccessControlStatement.AccountRevokeAll": {
        "grantees": "AccountName[]",
    },
    "AccessControlStatement.AccountRevokeProxy": {
        "proxy": "AccountName",
        "grantees": "AccountName[]",
    },
    "AccessControlStatement.AccountRevokeRole": {
        "roles": "AccountName[]",
        "grantees": "AccountName[]",
    },
    "PrivilegeLevelObject": {
        "object_type": "PrivilegeObjectType",
        "level": "PrivilegeLevel",
    },
    "PrivilegeLevel.Database": {
        "database": "Ident",
    },
    "PrivilegeLevel.Object": {
        "name": "ObjectName",
    },
    "GrantAs": {
        "user": "AccountName",
        "with_role": "WithRoleSpec",
    },
    "WithRoleSpec.Roles": {
        "roles": "AccountName[]",
    },
    "WithRoleSpec.All": {
        "except": "AccountName[]",
    },
    "Privileges.List": {
        "privileges": "Privilege[]",
    },
    "Privilege.Known": {
        "kind": "PrivilegeKind",
        "columns": "Ident[]",
    },
    "Privilege.Other": {
        "name": "Ident",
        "columns": "Ident[]",
    },
    "GrantObject.Table": {
        "names": "ObjectName[]",
    },
    "GrantObject.Named": {
        "kind": "NamedObjectKind",
        "names": "ObjectName[]",
    },
    "GrantObject.Routines": {
        "kind": "RoutineObjectKind",
        "routines": "RoutineSignature[]",
    },
    "GrantObject.AllInSchema": {
        "kind": "SchemaObjectKind",
        "schemas": "ObjectName[]",
    },
    "RoutineSignature": {
        "name": "ObjectName",
        "arg_types": "DataType[]",
    },
    "Grantee": {
        "spec": "RoleSpec",
    },
    "RoleSpec.Name": {
        "name": "Ident",
    },
    "CreateUser": {
        "users": "UserSpec[]",
        "default_roles": "AccountName[]",
        "require": "TlsRequirement",
        "resource_options": "ResourceLimit[]",
        "password_lock_options": "PasswordLockOption[]",
        "attribute": "UserAttribute",
    },
    "UserSpec": {
        "account": "AccountName",
        "auth": "AuthOption",
    },
    "AuthOption.Password": {
        "password": "Literal",
    },
    "AuthOption.Plugin": {
        "plugin": "Ident",
    },
    "AuthOption.PluginAs": {
        "plugin": "Ident",
        "auth_string": "Literal",
    },
    "AuthOption.PluginByPassword": {
        "plugin": "Ident",
        "password": "Literal",
    },
    "AuthOption.PluginByRandomPassword": {
        "plugin": "Ident",
    },
    "AlterUser.Modify": {
        "users": "AlterUserSpec[]",
        "require": "TlsRequirement",
        "resource_options": "ResourceLimit[]",
        "password_lock_options": "PasswordLockOption[]",
        "attribute": "UserAttribute",
    },
    "AlterUser.DefaultRole": {
        "user": "AccountName",
        "roles": "DefaultRoleTarget",
    },
    "AlterUserSpec": {
        "account": "AccountName",
        "auth": "AuthOption",
        "replace": "Literal",
    },
    "DefaultRoleTarget.Roles": {
        "roles": "AccountName[]",
    },
    "UserRoleList": {
        "kind": "UserRoleListKind",
        "names": "AccountName[]",
    },
    "TlsRequirement.Options": {
        "options": "TlsOption[]",
    },
    "TlsOption.Subject": {
        "value": "Literal",
    },
    "TlsOption.Issuer": {
        "value": "Literal",
    },
    "TlsOption.Cipher": {
        "value": "Literal",
    },
    "ResourceLimit.MaxQueriesPerHour": {
        "value": "Literal",
    },
    "ResourceLimit.MaxUpdatesPerHour": {
        "value": "Literal",
    },
    "ResourceLimit.MaxConnectionsPerHour": {
        "value": "Literal",
    },
    "ResourceLimit.MaxUserConnections": {
        "value": "Literal",
    },
    "PasswordLockOption.PasswordExpireInterval": {
        "days": "Literal",
    },
    "PasswordLockOption.PasswordHistory": {
        "count": "Literal",
    },
    "PasswordLockOption.PasswordReuseInterval": {
        "days": "Literal",
    },
    "PasswordLockOption.FailedLoginAttempts": {
        "count": "Literal",
    },
    "PasswordLockOption.PasswordLockTime": {
        "days": "Literal",
    },
    "UserAttribute.Comment": {
        "comment": "Literal",
    },
    "UserAttribute.Attribute": {
        "attribute": "Literal",
    },
    "CreateTable": {
        "temporary": "TemporaryTableKind",
        "name": "ObjectName",
        "body": "CreateTableBody",
        "inherits": "ObjectName[]",
        "partition_by": "PartitionSpec",
        "access_method": "Ident",
        "options": "CreateTableOption[]",
    },
    "CreateTableBody.Definition": {
        "elements": "TableElement[]",
    },
    "CreateTableBody.AsQuery": {
        "columns": "Ident[]",
        "query": "Query",
    },
    "CreateTableBody.AsExecute": {
        "columns": "Ident[]",
        "execute": "ExecuteStatement",
    },
    "CreateTableBody.PartitionOf": {
        "parent": "ObjectName",
        "elements": "TableElement[]",
        "bound": "PartitionBound",
    },
    "CreateTableBody.OfType": {
        "type_name": "ObjectName",
        "elements": "TableElement[]",
    },
    "CreateTableBody.LikeSource": {
        "source": "ObjectName",
    },
    "PartitionSpec": {
        "strategy": "PartitionStrategy",
        "columns": "PartitionElem[]",
    },
    "PartitionElem": {
        "expr": "Expr",
        "collation": "ObjectName",
        "opclass": "ObjectName",
    },
    "PartitionBound.List": {
        "values": "Expr[]",
    },
    "PartitionBound.Range": {
        "from": "Expr[]",
        "to": "Expr[]",
    },
    "PartitionBound.Hash": {
        "modulus": "Literal",
        "remainder": "Literal",
    },
    "TableElement.Column": {
        "column": "ColumnDef",
    },
    "TableElement.Constraint": {
        "constraint": "TableConstraintDef",
    },
    "TableElement.Like": {
        "source": "ObjectName",
        "options": "TableLikeOption[]",
    },
    "TableLikeOption": {
        "action": "TableLikeAction",
        "feature": "TableLikeFeature",
    },
    "ColumnDef": {
        "name": "Ident",
        "data_type": "DataType",
        "storage": "Ident",
        "compression": "Ident",
        "constraints": "ColumnConstraint[]",
    },
    "ColumnConstraint": {
        "name": "Ident",
        "option": "ColumnOption",
        "conflict": "ConflictResolution",
        "characteristics": "ConstraintCharacteristics",
    },
    "ColumnOption.Default": {
        "expr": "Expr",
    },
    "ColumnOption.Generated": {
        "generated": "GeneratedColumn",
    },
    "ColumnOption.Identity": {
        "identity": "IdentityColumn",
    },
    "ColumnOption.PrimaryKey": {
        "index_tablespace": "Ident",
    },
    "ColumnOption.Unique": {
        "index_tablespace": "Ident",
    },
    "ColumnOption.AutoIncrement": {
        "spelling": "AutoIncrementSpelling",
    },
    "ColumnOption.Collate": {
        "collation": "ObjectName",
    },
    "ColumnOption.Check": {
        "expr": "Expr",
    },
    "ColumnOption.References": {
        "reference": "ForeignKeyRef",
    },
    "ColumnOption.Other": {
        "ext": "NoExt",
    },
    "ForeignKeyRef": {
        "table": "ObjectName",
        "columns": "Ident[]",
        "match_type": "ForeignKeyMatch",
        "on_delete": "ReferentialAction",
        "on_update": "ReferentialAction",
    },
    "ReferentialAction.SetNull": {
        "columns": "Ident[]",
    },
    "ReferentialAction.SetDefault": {
        "columns": "Ident[]",
    },
    "GeneratedColumn": {
        "expr": "Expr",
        "storage": "GeneratedColumnStorage",
        "spelling": "GeneratedColumnSpelling",
    },
    "IdentityColumn": {
        "generation": "IdentityGeneration",
        "options": "IdentityOption[]",
    },
    "IdentityOption.StartWith": {
        "expr": "Expr",
    },
    "IdentityOption.IncrementBy": {
        "expr": "Expr",
    },
    "IdentityOption.MinValue": {
        "value": "Expr",
    },
    "IdentityOption.MaxValue": {
        "value": "Expr",
    },
    "IdentityOption.Cache": {
        "expr": "Expr",
    },
    "TableConstraintDef": {
        "name": "Ident",
        "constraint": "TableConstraint",
        "characteristics": "ConstraintCharacteristics",
    },
    "TableConstraint.PrimaryKey": {
        "columns": "IndexColumn[]",
        "include": "Ident[]",
    },
    "TableConstraint.Unique": {
        "columns": "IndexColumn[]",
        "include": "Ident[]",
    },
    "TableConstraint.Check": {
        "expr": "Expr",
    },
    "TableConstraint.Exclude": {
        "exclude": "ExcludeConstraint",
    },
    "TableConstraint.ForeignKey": {
        "columns": "Ident[]",
        "references": "ForeignKeyRef",
    },
    "TableConstraint.Other": {
        "ext": "NoExt",
    },
    "ExcludeConstraint": {
        "method": "Ident",
        "elements": "ExcludeElement[]",
        "include": "Ident[]",
        "with_params": "TableStorageParameter[]",
        "index_tablespace": "Ident",
        "predicate": "Expr",
    },
    "ExcludeElement": {
        "expr": "Expr",
        "collation": "ObjectName",
        "opclass": "ObjectName",
        "opclass_params": "TableStorageParameter[]",
        "operator": "ExcludeOperator",
    },
    "ExcludeOperator": {
        "schema": "ObjectName",
        "spelling": "NamedOperatorSpelling",
    },
    "CreateTableOption": {
        "kind": "CreateTableOptionKind",
    },
    "CreateTableOptionKind.ColocateWith": {
        "table": "ObjectName",
        "columns": "Ident[]",
    },
    "CreateTableOptionKind.InColocationGroup": {
        "group": "Ident",
        "columns": "Ident[]",
    },
    "CreateTableOptionKind.With": {
        "params": "TableStorageParameter[]",
    },
    "CreateTableOptionKind.OnCommit": {
        "action": "OnCommitAction",
    },
    "CreateTableOptionKind.Tablespace": {
        "tablespace": "Ident",
    },
    "CreateTableOptionKind.KeyValue": {
        "option": "TableOption",
    },
    "TableOption": {
        "name": "Ident",
        "value": "TableOptionValue",
    },
    "TableOptionValue.Word": {
        "word": "Ident",
    },
    "TableOptionValue.String": {
        "value": "Literal",
    },
    "TableOptionValue.Number": {
        "value": "Literal",
    },
    "TableStorageParameter": {
        "name": "ObjectName",
        "value": "Expr",
    },
    "AlterTable": {
        "name": "ObjectName",
        "actions": "AlterTableAction[]",
    },
    "AlterColumnTarget": {
        "parts": "Ident[]",
    },
    "AlterTableAction.SetColocationGroup": {
        "group": "Ident",
    },
    "AlterTableAction.AddColumn": {
        "target": "AlterColumnTarget",
        "column": "ColumnDef",
    },
    "AlterTableAction.DropColumn": {
        "name": "AlterColumnTarget",
        "behavior": "DropBehavior",
    },
    "AlterTableAction.AlterColumn": {
        "name": "Ident",
        "change": "AlterColumnAction",
    },
    "AlterTableAction.AddConstraint": {
        "constraint": "TableConstraintDef",
    },
    "AlterTableAction.DropConstraint": {
        "name": "Ident",
        "behavior": "DropBehavior",
    },
    "AlterTableAction.DropPrimaryKey": {
        "behavior": "DropBehavior",
    },
    "AlterTableAction.SetOptions": {
        "params": "TableStorageParameter[]",
    },
    "AlterTableAction.RenameColumn": {
        "name": "AlterColumnTarget",
        "new_name": "Ident",
    },
    "AlterTableAction.RenameConstraint": {
        "name": "Ident",
        "new_name": "Ident",
    },
    "AlterTableAction.RenameTable": {
        "new_name": "Ident",
    },
    "AlterTableAction.AttachPartition": {
        "partition": "ObjectName",
        "bound": "PartitionBound",
    },
    "AlterTableAction.DetachPartition": {
        "partition": "ObjectName",
        "mode": "DetachPartitionMode",
    },
    "AlterColumnAction.SetDefault": {
        "expr": "Expr",
    },
    "AlterColumnAction.AddIdentity": {
        "identity": "IdentityColumn",
    },
    "AlterColumnAction.SetDataType": {
        "data_type": "DataType",
        "using": "Expr",
    },
    "DropStatement": {
        "object_kind": "DropObjectKind",
        "names": "ObjectName[]",
        "behavior": "DropBehavior",
    },
    "DropTransform": {
        "object": "ObjectReference",
        "behavior": "DropBehavior",
    },
    "CommentTarget.Procedure": {
        "arg_types": "DataType[]",
    },
    "CommentOnStatement": {
        "target": "CommentTarget",
        "name": "ObjectName",
        "constraint_table": "ObjectName",
        "comment": "Literal",
    },
    "CreateSchema": {
        "name": "ObjectName",
        "authorization": "Ident",
        "elements": "Statement[]",
    },
    "CreateView": {
        "options": "ViewOptions",
        "temporary": "TemporaryTableKind",
        "name": "ObjectName",
        "columns": "Ident[]",
        "to": "ObjectName",
        "query": "Query",
        "check_option": "ViewCheckOption",
    },
    "RefreshMaterializedView": {
        "name": "ObjectName",
    },
    "CreateColocationGroup": {
        "name": "Ident",
        "partition": "ColocationPartitionKind",
        "columns": "Ident[]",
        "shards": "Literal",
    },
    "DropColocationGroup": {
        "name": "Ident",
    },
    "ViewOptions": {
        "algorithm": "ViewAlgorithm",
        "definer": "Definer",
        "sql_security": "SqlSecurityContext",
    },
    "AlterView": {
        "options": "ViewOptions",
        "name": "ObjectName",
        "columns": "Ident[]",
        "query": "Query",
        "check_option": "ViewCheckOption",
    },
    "CreateSecret": {
        "name": "ObjectName",
        "options": "SecretOption[]",
    },
    "SecretOption": {
        "name": "Ident",
        "value": "Expr",
    },
    "DropSecretStmt": {
        "persistence": "SecretPersistence",
        "name": "Ident",
        "storage": "Ident",
    },
    "CreateVirtualTable": {
        "name": "ObjectName",
        "module": "Ident",
        "args": "ModuleArg[]",
    },
    "CreateIndex": {
        "name": "Ident",
        "table": "ObjectName",
        "using": "Ident",
        "columns": "IndexColumn[]",
        "with_params": "TableStorageParameter[]",
        "predicate": "Expr",
    },
    "IndexColumn": {
        "expr": "Expr",
    },
    "CreateTrigger": {
        "temporary": "TemporaryTableKind",
        "name": "ObjectName",
        "timing": "TriggerTiming",
        "event": "TriggerEvent",
        "table": "ObjectName",
        "when": "Expr",
        "body": "Statement[]",
    },
    "TriggerEvent.Update": {
        "columns": "Ident[]",
    },
    "CreateStoredTrigger": {
        "definer": "Definer",
        "name": "ObjectName",
        "timing": "TriggerTiming",
        "event": "TriggerEvent",
        "table": "ObjectName",
        "ordering": "TriggerOrder",
        "body": "Statement",
    },
    "TriggerOrder.Follows": {
        "anchor": "Ident",
    },
    "TriggerOrder.Precedes": {
        "anchor": "Ident",
    },
    "CreateDatabase": {
        "name": "ObjectName",
    },
    "CreateFunction": {
        "definer": "Definer",
        "name": "ObjectName",
        "params": "FunctionParam[]",
        "returns": "DataType",
        "options": "FunctionOption[]",
        "body": "FunctionBody",
    },
    "FunctionParam": {
        "mode": "FunctionParamMode",
        "name": "Ident",
        "data_type": "DataType",
        "default": "FunctionParamDefault",
    },
    "FunctionParamDefault": {
        "spelling": "FunctionParamDefaultSpelling",
        "value": "Expr",
    },
    "FunctionOption.Language": {
        "name": "LanguageName",
    },
    "FunctionOption.As": {
        "body": "FunctionBody",
    },
    "FunctionOption.NullBehavior": {
        "behavior": "FunctionNullBehavior",
    },
    "FunctionOption.DataAccess": {
        "access": "SqlDataAccess",
    },
    "FunctionOption.SqlSecurity": {
        "context": "SqlSecurityContext",
    },
    "FunctionOption.Comment": {
        "comment": "Literal",
    },
    "FunctionBody.Definition": {
        "definition": "Literal",
    },
    "FunctionBody.Return": {
        "expr": "Expr",
    },
    "FunctionBody.Block": {
        "body": "Statement",
    },
    "Definer.Account": {
        "user": "Ident",
        "host": "Ident",
    },
    "CreateProcedure": {
        "definer": "Definer",
        "name": "ObjectName",
        "params": "FunctionParam[]",
        "characteristics": "FunctionOption[]",
        "body": "Statement",
    },
    "AlterRoutine": {
        "kind": "RoutineKind",
        "name": "ObjectName",
        "characteristics": "FunctionOption[]",
    },
    "EventSchedule.At": {
        "at": "Expr",
    },
    "EventSchedule.Every": {
        "value": "Expr",
        "unit": "IntervalFields",
        "starts": "Expr",
        "ends": "Expr",
    },
    "CreateEvent": {
        "definer": "Definer",
        "name": "ObjectName",
        "schedule": "EventSchedule",
        "on_completion": "EventOnCompletion",
        "status": "EventStatus",
        "comment": "Literal",
        "body": "Statement",
    },
    "AlterEvent": {
        "definer": "Definer",
        "name": "ObjectName",
        "schedule": "EventSchedule",
        "on_completion": "EventOnCompletion",
        "rename_to": "ObjectName",
        "status": "EventStatus",
        "comment": "Literal",
        "body": "Statement",
    },
    "DropEvent": {
        "name": "ObjectName",
    },
    "DropDatabase": {
        "spelling": "DatabaseKeyword",
        "name": "Ident",
    },
    "DropIndexOnTable": {
        "name": "Ident",
        "table": "ObjectName",
        "options": "IndexLockAlgorithmOption[]",
    },
    "IndexLockAlgorithmOption.Algorithm": {
        "value": "IndexAlgorithm",
    },
    "IndexLockAlgorithmOption.Lock": {
        "value": "IndexLock",
    },
    "CreateMacro": {
        "temporary": "TemporaryTableKind",
        "spelling": "MacroSpelling",
        "name": "ObjectName",
        "params": "MacroParam[]",
        "body": "MacroBody",
    },
    "MacroParam": {
        "name": "Ident",
        "default": "Expr",
    },
    "MacroBody.Scalar": {
        "expr": "Expr",
    },
    "MacroBody.Table": {
        "query": "Query",
    },
    "CreateType": {
        "temporary": "TemporaryTableKind",
        "name": "ObjectName",
        "definition": "CreateTypeDefinition",
    },
    "CreateTypeDefinition.Enum": {
        "labels": "Literal[]",
    },
    "CreateTypeDefinition.EnumFromQuery": {
        "query": "Query",
    },
    "CreateTypeDefinition.Alias": {
        "data_type": "DataType",
    },
    "CreateSequence": {
        "temporary": "TemporaryTableKind",
        "name": "ObjectName",
        "options": "IdentityOption[]",
    },
    "CreateExtension": {
        "name": "Ident",
        "options": "CreateExtensionOption[]",
    },
    "CreateExtensionOption.Schema": {
        "name": "Ident",
    },
    "CreateExtensionOption.Version": {
        "version": "ExtensionVersion",
    },
    "ExtensionVersion.Word": {
        "word": "Ident",
    },
    "ExtensionVersion.String": {
        "value": "Literal",
    },
    "AlterExtension": {
        "name": "Ident",
        "action": "AlterExtensionAction",
    },
    "AlterExtensionAction.Update": {
        "version": "ExtensionVersion",
    },
    "AlterExtensionAction.Change": {
        "member": "ObjectReference",
    },
    "AlterDatabase": {
        "name": "Ident",
        "action": "AlterDatabaseAction",
    },
    "AlterDatabaseAction.SetAlias": {
        "new_name": "Ident",
    },
    "AlterSequence": {
        "name": "ObjectName",
        "options": "AlterSequenceOption[]",
    },
    "AlterSequenceOption.Common": {
        "option": "IdentityOption",
    },
    "AlterSequenceOption.Restart": {
        "value": "Expr",
    },
    "AlterSequenceOption.As": {
        "data_type": "DataType",
    },
    "AlterSequenceOption.OwnedBy": {
        "owner": "ObjectName",
    },
    "AlterSequenceOption.SequenceName": {
        "name": "ObjectName",
    },
    "AlterObjectSchema": {
        "object_type": "SchemaRelocationObject",
        "name": "ObjectName",
        "new_schema": "Ident",
    },
    "ObjectReference.Named": {
        "kind": "ObjectRefKind",
        "name": "ObjectName",
    },
    "ObjectReference.Routine": {
        "kind": "RoutineObjectKind",
        "signature": "RoutineSignature",
    },
    "ObjectReference.Aggregate": {
        "name": "ObjectName",
        "args": "AggregateArgs",
    },
    "ObjectReference.Operator": {
        "schema": "ObjectName",
        "args": "OperatorArgs",
    },
    "ObjectReference.OperatorClass": {
        "name": "ObjectName",
        "access_method": "Ident",
    },
    "ObjectReference.Cast": {
        "from": "DataType",
        "to": "DataType",
    },
    "ObjectReference.Type": {
        "name": "DataType",
    },
    "ObjectReference.Transform": {
        "type_name": "DataType",
        "language": "Ident",
    },
    "ObjectReference.Trigger": {
        "name": "Ident",
        "table": "ObjectName",
    },
    "AggregateArgs.Types": {
        "direct": "DataType[]",
        "order_by": "DataType[]",
    },
    "OperatorArgs": {
        "left": "DataType",
        "right": "DataType",
    },
    "AlterObjectDepends": {
        "object": "ObjectReference",
        "extension": "Ident",
    },
    "CreateServer": {
        "name": "Ident",
        "wrapper": "Ident",
        "options": "ServerOption[]",
    },
    "AlterServer": {
        "name": "Ident",
        "options": "ServerOption[]",
    },
    "DropServer": {
        "name": "Ident",
    },
    "ServerOption": {
        "kind": "ServerOptionKind",
        "value": "Literal",
    },
    "AlterInstance": {
        "action": "AlterInstanceAction",
    },
    "AlterInstanceAction.ReloadTls": {
        "channel": "Ident",
    },
    "CreateSpatialReferenceSystem": {
        "srid": "Literal",
        "attributes": "SrsAttribute[]",
    },
    "SrsAttribute.Name": {
        "value": "Literal",
    },
    "SrsAttribute.Definition": {
        "value": "Literal",
    },
    "SrsAttribute.Organization": {
        "organization": "Literal",
        "identifier": "Literal",
    },
    "SrsAttribute.Description": {
        "value": "Literal",
    },
    "DropSpatialReferenceSystem": {
        "srid": "Literal",
    },
    "CreateResourceGroup": {
        "name": "Ident",
        "group_type": "ResourceGroupType",
        "vcpu": "ResourceGroupVcpu",
        "thread_priority": "ResourceGroupThreadPriority",
        "state": "ResourceGroupState",
    },
    "AlterResourceGroup": {
        "name": "Ident",
        "vcpu": "ResourceGroupVcpu",
        "thread_priority": "ResourceGroupThreadPriority",
        "state": "ResourceGroupState",
    },
    "DropResourceGroup": {
        "name": "Ident",
    },
    "ResourceGroupVcpu": {
        "ranges": "VcpuRange[]",
    },
    "VcpuRange": {
        "start": "Literal",
        "end": "Literal",
    },
    "ResourceGroupThreadPriority": {
        "value": "Literal",
    },
    "AlterDatabaseOptions": {
        "spelling": "DatabaseKeyword",
        "name": "Ident",
        "options": "AlterDatabaseOption[]",
    },
    "AlterDatabaseOption.CharacterSet": {
        "keyword": "CharsetKeyword",
        "charset": "Ident",
    },
    "AlterDatabaseOption.Collate": {
        "collation": "Ident",
    },
    "AlterDatabaseOption.Encryption": {
        "value": "Literal",
    },
    "AlterDatabaseOption.ReadOnly": {
        "value": "ReadOnlyValue",
    },
    "SizeLiteral": {
        "unit": "SizeUnit",
    },
    "TablespaceOption.Size": {
        "kind": "TablespaceSizeOption",
        "size": "SizeLiteral",
    },
    "TablespaceOption.Nodegroup": {
        "value": "Literal",
    },
    "TablespaceOption.Engine": {
        "name": "Ident",
    },
    "TablespaceOption.Comment": {
        "value": "Literal",
    },
    "TablespaceOption.Encryption": {
        "value": "Literal",
    },
    "TablespaceOption.EngineAttribute": {
        "value": "Literal",
    },
    "CreateTablespace": {
        "name": "Ident",
        "datafile": "Literal",
        "use_logfile_group": "Ident",
        "options": "TablespaceOption[]",
    },
    "AlterTablespace": {
        "name": "Ident",
        "action": "AlterTablespaceAction",
    },
    "AlterTablespaceAction.AddDatafile": {
        "datafile": "Literal",
        "options": "TablespaceOption[]",
    },
    "AlterTablespaceAction.DropDatafile": {
        "datafile": "Literal",
        "options": "TablespaceOption[]",
    },
    "AlterTablespaceAction.Rename": {
        "new_name": "Ident",
    },
    "AlterTablespaceAction.Options": {
        "options": "TablespaceOption[]",
    },
    "AlterTablespaceAction.SetState": {
        "state": "UndoTablespaceState",
        "options": "TablespaceOption[]",
    },
    "DropTablespace": {
        "name": "Ident",
        "options": "TablespaceOption[]",
    },
    "CreateLogfileGroup": {
        "name": "Ident",
        "undofile": "Literal",
        "options": "TablespaceOption[]",
    },
    "AlterLogfileGroup": {
        "name": "Ident",
        "undofile": "Literal",
        "options": "TablespaceOption[]",
    },
    "DropLogfileGroup": {
        "name": "Ident",
        "options": "TablespaceOption[]",
    },
    "Insert": {
        "verb": "InsertVerb",
        "modifier": "InsertModifier",
        "or_action": "ConflictResolution",
        "with": "With",
        "target": "InsertTarget",
        "column_matching": "InsertColumnMatching",
        "overriding": "InsertOverriding",
        "source": "InsertSource",
        "row_alias": "TableAlias",
        "upsert": "Upsert",
        "returning": "Returning",
    },
    "InsertTarget": {
        "name": "ObjectName",
        "alias": "Ident",
        "alias_spelling": "AliasSpelling",
        "columns": "Ident[]",
    },
    "InsertSource.DefaultValues": {
        "default": "DefaultValue",
    },
    "InsertSource.Values": {
        "values": "InsertValues",
    },
    "InsertSource.Query": {
        "query": "Query",
    },
    "InsertSource.Set": {
        "assignments": "UpdateAssignment[]",
    },
    "InsertValues": {
        "rows": "InsertValue[][]",
    },
    "InsertValue.Expr": {
        "expr": "Expr",
    },
    "InsertValue.Default": {
        "default": "DefaultValue",
    },
    "DmlTarget": {
        "name": "ObjectName",
        "inheritance": "RelationInheritance",
        "alias": "Ident",
        "alias_spelling": "AliasSpelling",
    },
    "Update": {
        "with": "With",
        "or_action": "ConflictResolution",
        "target": "DmlTarget",
        "target_joins": "Join[]",
        "assignments": "UpdateAssignment[]",
        "from": "TableWithJoins[]",
        "selection": "DmlSelection",
        "order_by": "OrderByExpr[]",
        "limit": "Limit",
        "returning": "Returning",
    },
    "UpdateAssignment.Single": {
        "target": "ObjectName",
        "value": "UpdateValue",
    },
    "UpdateAssignment.Tuple": {
        "targets": "ObjectName[]",
        "source": "UpdateTupleSource",
    },
    "UpdateValue.Expr": {
        "expr": "Expr",
    },
    "UpdateValue.Default": {
        "default": "DefaultValue",
    },
    "UpdateTupleSource.Row": {
        "values": "UpdateValue[]",
    },
    "UpdateTupleSource.Subquery": {
        "query": "Query",
    },
    "UpdateTupleSource.Default": {
        "default": "DefaultValue",
    },
    "Delete": {
        "with": "With",
        "target": "DmlTarget",
        "additional_targets": "DmlTarget[]",
        "target_joins": "Join[]",
        "using": "TableWithJoins[]",
        "selection": "DmlSelection",
        "order_by": "OrderByExpr[]",
        "limit": "Limit",
        "returning": "Returning",
    },
    "DmlSelection.Where": {
        "condition": "Expr",
    },
    "DmlSelection.CurrentOf": {
        "cursor": "Ident",
    },
    "Returning": {
        "items": "SelectItem[]",
    },
    "Upsert.OnConflict": {
        "conflict": "OnConflict",
    },
    "Upsert.OnDuplicateKeyUpdate": {
        "assignments": "UpdateAssignment[]",
    },
    "OnConflict": {
        "target": "ConflictTarget",
        "action": "ConflictAction",
    },
    "ConflictTarget.Index": {
        "columns": "Expr[]",
        "predicate": "Expr",
    },
    "ConflictTarget.Constraint": {
        "name": "Ident",
    },
    "ConflictAction.Update": {
        "assignments": "UpdateAssignment[]",
        "selection": "Expr",
    },
    "Merge": {
        "with": "With",
        "target": "DmlTarget",
        "using": "TableWithJoins",
        "on": "Expr",
        "clauses": "MergeWhenClause[]",
        "returning": "Returning",
    },
    "MergeWhenClause": {
        "match_kind": "MergeMatchKind",
        "condition": "Expr",
        "action": "MergeAction",
    },
    "MergeAction.Insert": {
        "columns": "Ident[]",
        "overriding": "InsertOverriding",
        "values": "InsertValue[]",
        "additional_rows": "InsertValue[][]",
    },
    "MergeAction.InsertDefault": {
        "default": "DefaultValue",
    },
    "MergeAction.Update": {
        "assignments": "UpdateAssignment[]",
    },
    "Expr.Column": {
        "name": "ObjectName",
    },
    "Expr.Literal": {
        "literal": "Literal",
    },
    "Expr.BinaryOp": {
        "left": "Expr",
        "op": "BinaryOperator",
        "right": "Expr",
    },
    "Expr.UnaryOp": {
        "op": "UnaryOperator",
        "expr": "Expr",
    },
    "Expr.Function": {
        "call": "FunctionCall",
    },
    "Expr.Case": {
        "case": "CaseExpr",
    },
    "Expr.Extract": {
        "extract": "ExtractExpr",
    },
    "Expr.Cast": {
        "expr": "Expr",
        "data_type": "DataType",
        "syntax": "CastSyntax",
    },
    "Expr.IsNull": {
        "expr": "Expr",
        "spelling": "NullTestSpelling",
    },
    "Expr.IsTruth": {
        "expr": "Expr",
        "value": "TruthValue",
    },
    "Expr.IsNormalized": {
        "expr": "Expr",
        "form": "NormalizationForm",
    },
    "Expr.Between": {
        "expr": "Expr",
        "low": "Expr",
        "high": "Expr",
    },
    "Expr.Like": {
        "expr": "Expr",
        "pattern": "Expr",
        "escape": "Expr",
        "spelling": "LikeSpelling",
    },
    "Expr.InList": {
        "expr": "Expr",
        "list": "Expr[]",
    },
    "Expr.InSubquery": {
        "expr": "Expr",
        "subquery": "Query",
    },
    "Expr.InExpr": {
        "expr": "Expr",
        "rhs": "Expr",
    },
    "Expr.Exists": {
        "query": "Query",
    },
    "Expr.QuantifiedComparison": {
        "left": "Expr",
        "op": "BinaryOperator",
        "quantifier": "Quantifier",
        "subquery": "Query",
    },
    "Expr.QuantifiedList": {
        "left": "Expr",
        "op": "BinaryOperator",
        "quantifier": "Quantifier",
        "array": "Expr",
    },
    "Expr.QuantifiedLike": {
        "left": "Expr",
        "pattern": "Expr",
        "quantifier": "Quantifier",
        "spelling": "LikeSpelling",
    },
    "Expr.Subquery": {
        "query": "Query",
    },
    "Expr.Parameter": {
        "kind": "ParameterKind",
    },
    "Expr.SessionVariable": {
        "kind": "SessionVariableKind",
    },
    "Expr.Subscript": {
        "subscript": "SubscriptExpr",
    },
    "Expr.SemiStructuredAccess": {
        "semi_structured_access": "SemiStructuredAccessExpr",
    },
    "Expr.Collate": {
        "collate": "CollateExpr",
    },
    "Expr.Interval": {
        "value": "Expr",
        "unit": "IntervalFields",
    },
    "Expr.AtTimeZone": {
        "at_time_zone": "AtTimeZoneExpr",
    },
    "Expr.Array": {
        "array": "ArrayExpr",
    },
    "Expr.Struct": {
        "struct": "StructExpr",
    },
    "Expr.StructConstructor": {
        "constructor": "StructConstructorExpr",
    },
    "Expr.Map": {
        "map": "MapExpr",
    },
    "Expr.Row": {
        "row": "RowExpr",
    },
    "Expr.FieldSelection": {
        "field_selection": "FieldSelectionExpr",
    },
    "Expr.NamedOperator": {
        "named_operator": "NamedOperatorExpr",
    },
    "Expr.PrefixOperator": {
        "prefix_operator": "PrefixOperatorExpr",
    },
    "Expr.PostfixOperator": {
        "postfix_operator": "PostfixOperatorExpr",
    },
    "Expr.Lambda": {
        "lambda": "LambdaExpr",
    },
    "Expr.Columns": {
        "qualifier": "ObjectName",
        "pattern": "Expr",
        "options": "WildcardOptions",
        "spelling": "ColumnsSpelling",
    },
    "Expr.SpecialFunction": {
        "keyword": "SpecialFunctionKeyword",
    },
    "Expr.JsonFunc": {
        "json_func": "JsonFuncExpr",
    },
    "Expr.JsonObject": {
        "json_object": "JsonObjectExpr",
    },
    "Expr.JsonArray": {
        "json_array": "JsonArrayExpr",
    },
    "Expr.JsonAggregate": {
        "json_aggregate": "JsonAggregateExpr",
    },
    "Expr.JsonConstructor": {
        "json_constructor": "JsonConstructorExpr",
    },
    "Expr.IsJson": {
        "is_json": "IsJsonExpr",
    },
    "Expr.XmlFunc": {
        "xml_func": "XmlFunc",
    },
    "Expr.IsDocument": {
        "expr": "Expr",
    },
    "Expr.StringFunc": {
        "string_func": "StringFunc",
    },
    "Expr.Other": {
        "ext": "NoExt",
    },
    "SubscriptExpr": {
        "base": "Expr",
        "lower": "Expr",
        "upper": "Expr",
        "step": "Expr",
        "kind": "SubscriptKind",
    },
    "SemiStructuredAccessExpr": {
        "base": "Expr",
        "path": "SemiStructuredPathSegment[]",
    },
    "SemiStructuredPathSegment.Key": {
        "key": "Ident",
    },
    "SemiStructuredPathSegment.Index": {
        "index": "Expr",
    },
    "CollateExpr": {
        "expr": "Expr",
        "collation": "ObjectName",
    },
    "AtTimeZoneExpr": {
        "expr": "Expr",
        "zone": "Expr",
    },
    "ArrayExpr.Elements": {
        "elements": "Expr[]",
        "spelling": "ArraySpelling",
    },
    "ArrayExpr.Subquery": {
        "query": "Query",
    },
    "ArrayExpr.Comprehension": {
        "comprehension": "ListComprehension",
    },
    "ListComprehension": {
        "element": "Expr",
        "vars": "Ident[]",
        "source": "ComprehensionSource",
        "filter": "Expr",
    },
    "ComprehensionSource.Expr": {
        "expr": "Expr",
    },
    "ComprehensionSource.Star": {
        "options": "WildcardOptions",
    },
    "StructExpr": {
        "fields": "StructField[]",
    },
    "StructField": {
        "key_spelling": "StructKeySpelling",
        "value": "Expr",
    },
    "StructConstructorExpr": {
        "fields": "StructConstructorField[]",
        "args": "StructConstructorArg[]",
    },
    "StructConstructorField": {
        "name": "Ident",
        "ty": "DataType",
    },
    "StructConstructorArg": {
        "value": "Expr",
        "alias": "Ident",
    },
    "MapExpr": {
        "entries": "MapEntry[]",
    },
    "MapEntry": {
        "key": "Expr",
        "value": "Expr",
    },
    "RowExpr": {
        "fields": "Expr[]",
    },
    "FieldSelectionExpr": {
        "base": "Expr",
        "selector": "FieldSelector",
    },
    "FieldSelector.Field": {
        "field": "Ident",
    },
    "NamedOperatorExpr": {
        "left": "Expr",
        "schema": "ObjectName",
        "right": "Expr",
        "spelling": "NamedOperatorSpelling",
    },
    "PrefixOperatorExpr": {
        "operand": "Expr",
    },
    "PostfixOperatorExpr": {
        "operand": "Expr",
    },
    "LambdaExpr": {
        "params": "Ident[]",
        "spelling": "LambdaParamSpelling",
        "body": "Expr",
    },
    "ParameterKind.Named": {
        "sigil": "ParameterSigil",
    },
    "FunctionCall": {
        "name": "ObjectName",
        "quantifier": "SetQuantifier",
        "args": "FunctionArg[]",
        "order_by": "OrderByExpr[]",
        "within_group": "OrderByExpr[]",
        "separator": "Literal",
        "filter": "Expr",
        "filter_where": "FilterWhereSpelling",
        "over": "WindowSpec",
        "null_treatment": "NullTreatment",
        "window_tail": "WindowFunctionTail",
    },
    "FunctionArg": {
        "syntax": "ArgSyntax",
        "value": "Expr",
    },
    "WindowFunctionTail": {
        "from_first_last": "FromFirstLast",
        "null_treatment": "NullTreatment",
    },
    "CaseExpr": {
        "operand": "Expr",
        "when_clauses": "WhenClause[]",
        "else_result": "Expr",
    },
    "WhenClause": {
        "condition": "Expr",
        "result": "Expr",
    },
    "ExtractExpr": {
        "field": "Ident",
        "source": "Expr",
    },
    "JsonFormat": {
        "encoding": "JsonEncoding",
    },
    "JsonValueExpr": {
        "expr": "Expr",
        "format": "JsonFormat",
    },
    "JsonReturning": {
        "data_type": "DataType",
        "format": "JsonFormat",
    },
    "JsonPassingArg": {
        "value": "JsonValueExpr",
        "name": "Ident",
    },
    "JsonBehavior": {
        "kind": "JsonBehaviorKind",
        "default_expr": "Expr",
    },
    "JsonFuncExpr": {
        "kind": "JsonFuncKind",
        "context": "JsonValueExpr",
        "path": "Expr",
        "passing": "JsonPassingArg[]",
        "returning": "JsonReturning",
        "wrapper": "JsonWrapperBehavior",
        "quotes": "JsonQuotesBehavior",
        "on_empty": "JsonBehavior",
        "on_error": "JsonBehavior",
    },
    "JsonKeyValue": {
        "key": "Expr",
        "value": "JsonValueExpr",
        "spelling": "JsonKeyValueSpelling",
    },
    "JsonObjectExpr": {
        "entries": "JsonKeyValue[]",
        "null_clause": "JsonNullClause",
        "returning": "JsonReturning",
    },
    "JsonArrayBody.Values": {
        "items": "JsonValueExpr[]",
        "null_clause": "JsonNullClause",
    },
    "JsonArrayBody.Query": {
        "query": "Query",
        "format": "JsonFormat",
    },
    "JsonArrayExpr": {
        "body": "JsonArrayBody",
        "returning": "JsonReturning",
    },
    "JsonAggregateBody.Object": {
        "entry": "JsonKeyValue",
    },
    "JsonAggregateBody.Array": {
        "value": "JsonValueExpr",
        "order_by": "OrderByExpr[]",
    },
    "JsonAggregateExpr": {
        "body": "JsonAggregateBody",
        "null_clause": "JsonNullClause",
        "returning": "JsonReturning",
        "filter": "Expr",
        "over": "WindowSpec",
    },
    "JsonConstructorExpr": {
        "kind": "JsonConstructorKind",
        "value": "JsonValueExpr",
        "returning": "JsonReturning",
    },
    "IsJsonExpr": {
        "expr": "Expr",
        "item_type": "JsonItemType",
    },
    "XmlFunc.Element": {
        "name": "Ident",
        "attributes": "XmlAttribute[]",
        "content": "Expr[]",
    },
    "XmlFunc.Forest": {
        "elements": "XmlAttribute[]",
    },
    "XmlFunc.Concat": {
        "args": "Expr[]",
    },
    "XmlFunc.Parse": {
        "option": "XmlDocumentOrContent",
        "arg": "Expr",
        "whitespace": "XmlWhitespaceOption",
    },
    "XmlFunc.Pi": {
        "name": "Ident",
        "content": "Expr",
    },
    "XmlFunc.Root": {
        "arg": "Expr",
        "version": "Expr",
        "standalone": "XmlStandalone",
    },
    "XmlFunc.Serialize": {
        "option": "XmlDocumentOrContent",
        "arg": "Expr",
        "data_type": "DataType",
        "indent": "XmlIndentOption",
    },
    "XmlFunc.Exists": {
        "path": "Expr",
        "mechanism_before": "XmlPassingMechanism",
        "arg": "Expr",
        "mechanism_after": "XmlPassingMechanism",
    },
    "XmlAttribute": {
        "value": "Expr",
        "name": "Ident",
    },
    "StringFunc.Substring": {
        "expr": "Expr",
        "start": "Expr",
        "count": "Expr",
    },
    "StringFunc.SubstringSimilar": {
        "expr": "Expr",
        "pattern": "Expr",
        "escape": "Expr",
    },
    "StringFunc.Position": {
        "substr": "Expr",
        "string": "Expr",
    },
    "StringFunc.Overlay": {
        "target": "Expr",
        "replacement": "Expr",
        "start": "Expr",
        "count": "Expr",
    },
    "StringFunc.Trim": {
        "side": "TrimSide",
        "trim_chars": "Expr",
        "sources": "Expr[]",
    },
    "StringFunc.CollationFor": {
        "expr": "Expr",
    },
    "StringFunc.ConvertUsing": {
        "expr": "Expr",
        "charset": "Ident",
    },
    "StringFunc.MatchAgainst": {
        "columns": "Expr[]",
        "against": "Expr",
        "modifier": "MatchSearchModifier",
    },
    "StringFunc.CeilTo": {
        "expr": "Expr",
        "field": "Ident",
        "spelling": "CeilSpelling",
    },
    "StringFunc.FloorTo": {
        "expr": "Expr",
        "field": "Ident",
    },
    "Ident": {
        "quote": "QuoteStyle",
    },
    "Literal": {
        "kind": "LiteralKind",
    },
    "LiteralKind.Time": {
        "time_zone": "TimeZone",
    },
    "LiteralKind.Timestamp": {
        "time_zone": "TimeZone",
    },
    "LiteralKind.Interval": {
        "fields": "IntervalFields",
    },
    "LiteralKind.BitString": {
        "radix": "BitStringRadix",
    },
    "MatchRecognize": {
        "source": "TableFactor",
        "partition_by": "Expr[]",
        "order_by": "OrderByExpr[]",
        "measures": "Measure[]",
        "rows_per_match": "RowsPerMatch",
        "after_match_skip": "AfterMatchSkip",
        "pattern": "MatchRecognizePattern",
        "subsets": "SubsetDefinition[]",
        "define": "SymbolDefinition[]",
    },
    "Measure": {
        "expr": "Expr",
        "alias": "Ident",
    },
    "AfterMatchSkip.ToFirst": {
        "symbol": "Ident",
    },
    "AfterMatchSkip.ToLast": {
        "symbol": "Ident",
    },
    "SubsetDefinition": {
        "name": "Ident",
        "members": "Ident[]",
    },
    "SymbolDefinition": {
        "symbol": "Ident",
        "definition": "Expr",
    },
    "MatchRecognizePattern.Symbol": {
        "symbol": "Ident",
    },
    "MatchRecognizePattern.Concat": {
        "patterns": "MatchRecognizePattern[]",
    },
    "MatchRecognizePattern.Alternation": {
        "patterns": "MatchRecognizePattern[]",
    },
    "MatchRecognizePattern.Group": {
        "pattern": "MatchRecognizePattern",
    },
    "MatchRecognizePattern.Exclude": {
        "pattern": "MatchRecognizePattern",
    },
    "MatchRecognizePattern.Permute": {
        "patterns": "MatchRecognizePattern[]",
    },
    "MatchRecognizePattern.Repetition": {
        "pattern": "MatchRecognizePattern",
        "quantifier": "RepetitionQuantifier",
    },
    "PipeOperator.Where": {
        "predicate": "Expr",
    },
    "PipeOperator.Select": {
        "items": "SelectItem[]",
    },
    "PipeOperator.Extend": {
        "items": "SelectItem[]",
    },
    "PipeOperator.As": {
        "alias": "TableAlias",
    },
    "PipeOperator.OrderBy": {
        "keys": "OrderByExpr[]",
    },
    "PipeOperator.Limit": {
        "count": "Expr",
        "offset": "Expr",
    },
    "PipeOperator.Join": {
        "join": "Join",
    },
    "PipeOperator.SetOperation": {
        "op": "SetOperator",
        "quantifier": "SetQuantifier",
        "queries": "Query[]",
    },
    "PipeOperator.Set": {
        "assignments": "UpdateAssignment[]",
    },
    "PipeOperator.Call": {
        "call": "FunctionCall",
        "alias": "TableAlias",
    },
    "PipeOperator.Aggregate": {
        "aggregates": "PipeAggregateExpr[]",
        "group_by": "PipeAggregateExpr[]",
    },
    "PipeOperator.Drop": {
        "columns": "Ident[]",
    },
    "PipeOperator.Rename": {
        "renames": "PipeRenameItem[]",
    },
    "PipeOperator.Pivot": {
        "aggregates": "PivotExpr[]",
        "column": "PivotColumn",
    },
    "PipeOperator.Unpivot": {
        "value": "Ident[]",
        "name": "Ident[]",
        "columns": "UnpivotColumn[]",
    },
    "PipeOperator.TableSample": {
        "sample": "TableSample",
    },
    "PipeAggregateExpr": {
        "expr": "Expr",
        "alias": "Ident",
    },
    "PipeRenameItem": {
        "old": "Ident",
        "new": "Ident",
    },
    "Pivot": {
        "source": "TableFactor",
        "aggregates": "PivotExpr[]",
        "pivot_on": "PivotColumn[]",
        "group_by": "Expr[]",
        "with": "With",
        "order_by": "OrderByExpr[]",
        "order_by_all": "OrderByAll",
        "limit": "Limit",
        "default_on_null": "Expr",
        "spelling": "PivotSpelling",
    },
    "Unpivot": {
        "source": "TableFactor",
        "value": "Ident[]",
        "name": "Ident[]",
        "columns": "UnpivotColumn[]",
        "null_inclusion": "NullInclusion",
        "with": "With",
        "order_by": "OrderByExpr[]",
        "order_by_all": "OrderByAll",
        "limit": "Limit",
        "spelling": "UnpivotSpelling",
    },
    "PivotExpr": {
        "expr": "Expr",
        "alias": "Ident",
        "alias_spelling": "AliasSpelling",
    },
    "PivotColumn": {
        "expr": "Expr",
        "values": "PivotExpr[]",
        "enum_source": "Ident",
        "value_source": "PivotValueSource",
    },
    "PivotValueSource.Any": {
        "order_by": "OrderByExpr[]",
    },
    "PivotValueSource.Subquery": {
        "query": "Query",
    },
    "UnpivotColumn": {
        "columns": "Expr[]",
        "alias": "Ident",
        "alias_spelling": "AliasSpelling",
    },
    "Query": {
        "with": "With",
        "body": "SetExpr",
        "order_by": "OrderByExpr[]",
        "order_by_all": "OrderByAll",
        "limit_by": "LimitBy",
        "limit": "Limit",
        "settings": "Setting[]",
        "format": "FormatClause",
        "locking": "LockingClause[]",
        "pipe_operators": "PipeOperator[]",
        "for_clause": "ForClause",
    },
    "LockingClause": {
        "strength": "LockStrength",
        "of": "ObjectName[]",
        "wait": "LockWait",
        "spelling": "LockingSpelling",
    },
    "SetExpr.Select": {
        "select": "Select",
    },
    "SetExpr.Values": {
        "values": "Values",
    },
    "SetExpr.Query": {
        "query": "Query",
    },
    "SetExpr.SetOperation": {
        "op": "SetOperator",
        "left": "SetExpr",
        "right": "SetExpr",
    },
    "SetExpr.Pivot": {
        "pivot": "Pivot",
    },
    "SetExpr.Unpivot": {
        "unpivot": "Unpivot",
    },
    "With": {
        "ctes": "Cte[]",
    },
    "Cte": {
        "name": "Ident",
        "columns": "Ident[]",
        "using_key": "Ident[]",
        "body": "CteBody",
        "search": "CteSearchClause",
        "cycle": "CteCycleClause",
    },
    "CteSearchClause": {
        "columns": "Ident[]",
        "set_column": "Ident",
    },
    "CteCycleClause": {
        "columns": "Ident[]",
        "mark_column": "Ident",
        "mark": "CteCycleMark",
        "path_column": "Ident",
    },
    "CteCycleMark": {
        "value": "Expr",
        "default": "Expr",
    },
    "CteBody.Query": {
        "query": "Query",
    },
    "CteBody.Insert": {
        "insert": "Insert",
    },
    "CteBody.Update": {
        "update": "Update",
    },
    "CteBody.Delete": {
        "delete": "Delete",
    },
    "CteBody.Merge": {
        "merge": "Merge",
    },
    "Values": {
        "rows": "ValuesItem[][]",
    },
    "ValuesItem.Expr": {
        "expr": "Expr",
    },
    "ValuesItem.Default": {
        "default": "DefaultValue",
    },
    "Select": {
        "distinct": "SelectDistinct",
        "projection": "SelectItem[]",
        "into": "IntoTarget",
        "from": "TableWithJoins[]",
        "lateral_views": "LateralView[]",
        "selection": "Expr",
        "connect_by": "HierarchicalClause",
        "group_by": "GroupByItem[]",
        "group_by_quantifier": "SetQuantifier",
        "group_by_all": "GroupByAllSpelling",
        "having": "Expr",
        "windows": "NamedWindow[]",
        "qualify": "Expr",
        "sample": "SampleClause",
        "spelling": "SelectSpelling",
    },
    "IntoTarget": {
        "temporary": "TemporaryTableKind",
        "name": "ObjectName",
    },
    "GroupByItem.Expr": {
        "expr": "Expr",
    },
    "GroupByItem.Rollup": {
        "exprs": "Expr[]",
        "spelling": "RollupSpelling",
    },
    "GroupByItem.Cube": {
        "exprs": "Expr[]",
    },
    "GroupByItem.GroupingSets": {
        "sets": "GroupByItem[]",
    },
    "SelectItem.Wildcard": {
        "options": "WildcardOptions",
        "alias": "Ident",
        "alias_spelling": "AliasSpelling",
    },
    "SelectItem.QualifiedWildcard": {
        "name": "ObjectName",
        "options": "WildcardOptions",
        "alias": "Ident",
        "alias_spelling": "AliasSpelling",
    },
    "SelectItem.Expr": {
        "expr": "Expr",
        "alias": "Ident",
        "alias_spelling": "AliasSpelling",
    },
    "WildcardOptions": {
        "exclude": "ObjectName[]",
        "replace": "WildcardReplace[]",
        "rename": "WildcardRename[]",
    },
    "WildcardReplace": {
        "expr": "Expr",
        "column": "Ident",
    },
    "WildcardRename": {
        "column": "ObjectName",
        "alias": "Ident",
    },
    "SelectDistinct.Quantifier": {
        "quantifier": "SetQuantifier",
    },
    "SelectDistinct.On": {
        "exprs": "Expr[]",
    },
    "TableWithJoins": {
        "relation": "TableFactor",
        "joins": "Join[]",
    },
    "TableAlias": {
        "name": "Ident",
        "columns": "Ident[]",
        "spelling": "AliasSpelling",
    },
    "TableSample": {
        "method": "ObjectName",
        "args": "Expr[]",
        "repeatable": "Expr",
    },
    "TableVersion.ForSystemTimeAsOf": {
        "point": "Expr",
    },
    "TableVersion.ForSystemTimeFromTo": {
        "start": "Expr",
        "end": "Expr",
    },
    "TableVersion.ForSystemTimeBetween": {
        "start": "Expr",
        "end": "Expr",
    },
    "TableVersion.ForSystemTimeContainedIn": {
        "start": "Expr",
        "end": "Expr",
    },
    "TableVersion.VersionAsOf": {
        "version": "Expr",
    },
    "TableVersion.TimestampAsOf": {
        "point": "Expr",
    },
    "SampleClause": {
        "method": "ObjectName",
        "size": "Literal",
        "unit": "SampleUnit",
        "seed": "Literal",
    },
    "TableFunctionColumn": {
        "name": "Ident",
        "data_type": "DataType",
    },
    "RowsFromItem": {
        "function": "FunctionCall",
        "column_defs": "TableFunctionColumn[]",
    },
    "IndexHint": {
        "action": "IndexHintAction",
        "keyword": "IndexHintKeyword",
        "scope": "IndexHintScope",
        "indexes": "Ident[]",
    },
    "IndexedBy.Named": {
        "index": "Ident",
    },
    "TableHint.Keyword": {
        "keyword": "TableHintKeyword",
    },
    "TableHint.Index": {
        "indexes": "Ident[]",
    },
    "TableHint.ForceSeek": {
        "target": "ForceSeekTarget",
    },
    "TableHint.Other": {
        "ident": "Ident",
    },
    "ForceSeekTarget": {
        "index": "Ident",
        "columns": "Ident[]",
    },
    "TableFactor.Table": {
        "name": "ObjectName",
        "inheritance": "RelationInheritance",
        "json_path": "SemiStructuredPathSegment[]",
        "version": "TableVersion",
        "partition": "Ident[]",
        "alias": "TableAlias",
        "indexed_by": "IndexedBy",
        "index_hints": "IndexHint[]",
        "sample": "TableSample",
        "table_hints": "TableHint[]",
    },
    "TableFactor.Derived": {
        "subquery": "Query",
        "alias": "TableAlias",
        "spelling": "DerivedSpelling",
    },
    "TableFactor.Function": {
        "function": "FunctionCall",
        "alias": "TableAlias",
        "column_defs": "TableFunctionColumn[]",
    },
    "TableFactor.RowsFrom": {
        "functions": "RowsFromItem[]",
        "alias": "TableAlias",
    },
    "TableFactor.Unnest": {
        "array_exprs": "Expr[]",
        "alias": "TableAlias",
        "column_defs": "TableFunctionColumn[]",
        "with_offset_alias": "Ident",
    },
    "TableFactor.NestedJoin": {
        "table": "TableWithJoins",
        "alias": "TableAlias",
    },
    "TableFactor.SpecialFunction": {
        "keyword": "SpecialFunctionKeyword",
        "alias": "TableAlias",
    },
    "TableFactor.Pivot": {
        "pivot": "Pivot",
        "alias": "TableAlias",
    },
    "TableFactor.Unpivot": {
        "unpivot": "Unpivot",
        "alias": "TableAlias",
    },
    "TableFactor.MatchRecognize": {
        "match_recognize": "MatchRecognize",
        "alias": "TableAlias",
    },
    "TableFactor.ShowRef": {
        "show": "ShowRef",
        "alias": "TableAlias",
    },
    "TableFactor.JsonTable": {
        "json_table": "JsonTable",
        "alias": "TableAlias",
    },
    "TableFactor.XmlTable": {
        "xml_table": "XmlTable",
        "alias": "TableAlias",
    },
    "TableFactor.OpenJson": {
        "open_json": "OpenJson",
        "alias": "TableAlias",
    },
    "TableFactor.TableExpr": {
        "expr": "Expr",
        "alias": "TableAlias",
    },
    "TableFactor.Other": {
        "ext": "NoExt",
    },
    "ShowRef": {
        "kind": "ShowRefKind",
        "target": "ShowRefTarget",
    },
    "ShowRefTarget.Query": {
        "query": "Query",
    },
    "ShowRefTarget.Name": {
        "name": "ObjectName",
    },
    "JsonTable": {
        "context": "JsonValueExpr",
        "path": "Expr",
        "path_name": "Ident",
        "passing": "JsonPassingArg[]",
        "columns": "JsonTableColumn[]",
        "on_error": "JsonBehavior",
    },
    "JsonTableColumn.ForOrdinality": {
        "name": "Ident",
    },
    "JsonTableColumn.Regular": {
        "name": "Ident",
        "data_type": "DataType",
        "format": "JsonFormat",
        "path": "Expr",
        "wrapper": "JsonWrapperBehavior",
        "quotes": "JsonQuotesBehavior",
        "on_empty": "JsonBehavior",
        "on_error": "JsonBehavior",
    },
    "JsonTableColumn.Exists": {
        "name": "Ident",
        "data_type": "DataType",
        "path": "Expr",
        "on_error": "JsonBehavior",
    },
    "JsonTableColumn.Nested": {
        "path": "Expr",
        "path_name": "Ident",
        "columns": "JsonTableColumn[]",
    },
    "XmlTable": {
        "namespaces": "XmlNamespace[]",
        "row_expr": "Expr",
        "document": "Expr",
        "passing_mechanism_before": "XmlPassingMechanism",
        "passing_mechanism_after": "XmlPassingMechanism",
        "columns": "XmlTableColumn[]",
    },
    "XmlNamespace": {
        "uri": "Expr",
        "name": "Ident",
    },
    "XmlTableColumn.ForOrdinality": {
        "name": "Ident",
    },
    "XmlTableColumn.Regular": {
        "name": "Ident",
        "data_type": "DataType",
        "path": "Expr",
        "default": "Expr",
    },
    "OpenJson": {
        "json_expr": "Expr",
        "path": "Expr",
        "columns": "OpenJsonColumn[]",
    },
    "OpenJsonColumn": {
        "name": "Ident",
        "data_type": "DataType",
        "path": "Expr",
    },
    "Join": {
        "relation": "TableFactor",
        "operator": "JoinOperator",
    },
    "JoinOperator.Inner": {
        "constraint": "JoinConstraint",
    },
    "JoinOperator.LeftOuter": {
        "constraint": "JoinConstraint",
    },
    "JoinOperator.RightOuter": {
        "constraint": "JoinConstraint",
    },
    "JoinOperator.FullOuter": {
        "constraint": "JoinConstraint",
    },
    "JoinOperator.AsOf": {
        "kind": "AsOfJoinKind",
        "constraint": "JoinConstraint",
    },
    "JoinOperator.Semi": {
        "side": "SemiAntiSide",
        "constraint": "JoinConstraint",
    },
    "JoinOperator.Anti": {
        "side": "SemiAntiSide",
        "constraint": "JoinConstraint",
    },
    "JoinOperator.Apply": {
        "kind": "ApplyKind",
    },
    "JoinConstraint.On": {
        "expr": "Expr",
    },
    "JoinConstraint.Using": {
        "columns": "Ident[]",
        "alias": "Ident",
    },
    "OrderByExpr": {
        "expr": "Expr",
        "using": "OrderByUsing",
    },
    "OrderByUsing": {
        "schema": "ObjectName",
    },
    "Limit": {
        "limit": "Expr",
        "offset": "Expr",
        "syntax": "LimitSyntax",
        "percent": "LimitPercent",
        "fetch_spelling": "FetchSpelling",
    },
    "LimitBy": {
        "limit": "Expr",
        "offset": "Expr",
        "by": "Expr[]",
    },
    "Setting": {
        "name": "Ident",
        "value": "Expr",
    },
    "FormatClause": {
        "name": "Ident",
    },
    "ForClause.Xml": {
        "mode": "ForXmlMode",
        "elements": "ForXmlElements",
        "root": "ForRoot",
    },
    "ForClause.Json": {
        "mode": "ForJsonMode",
        "root": "ForRoot",
    },
    "ForXmlMode.Raw": {
        "name": "Literal",
    },
    "ForXmlMode.Path": {
        "name": "Literal",
    },
    "ForRoot": {
        "name": "Literal",
    },
    "LateralView": {
        "function": "FunctionCall",
        "alias": "Ident",
        "columns": "Ident[]",
    },
    "HierarchicalClause": {
        "start_with": "Expr",
        "connect_by": "Expr",
    },
    "ReplicationStatement.ChangeSource": {
        "options": "ChangeReplicationSourceOption[]",
        "channel": "Literal",
    },
    "ReplicationStatement.ChangeFilter": {
        "rules": "ReplicationFilterRule[]",
        "channel": "Literal",
    },
    "ReplicationStatement.StartReplica": {
        "threads": "ReplicaThreadOption[]",
        "until": "ReplicaUntilCondition[]",
        "user": "Literal",
        "password": "Literal",
        "default_auth": "Literal",
        "plugin_dir": "Literal",
        "channel": "Literal",
    },
    "ReplicationStatement.StopReplica": {
        "threads": "ReplicaThreadOption[]",
        "channel": "Literal",
    },
    "ReplicationStatement.StartGroupReplication": {
        "options": "GroupReplicationOption[]",
    },
    "ChangeReplicationSourceOption": {
        "name": "SourceOption",
        "value": "ChangeReplicationSourceOptionValue",
    },
    "ChangeReplicationSourceOptionValue.String": {
        "value": "Literal",
    },
    "ChangeReplicationSourceOptionValue.Number": {
        "value": "Literal",
    },
    "ChangeReplicationSourceOptionValue.NullableString": {
        "value": "Literal",
    },
    "ChangeReplicationSourceOptionValue.User": {
        "account": "AccountName",
    },
    "ChangeReplicationSourceOptionValue.ServerIds": {
        "ids": "Literal[]",
    },
    "ChangeReplicationSourceOptionValue.PrimaryKeyCheck": {
        "check": "RequirePrimaryKeyCheck",
    },
    "ChangeReplicationSourceOptionValue.AssignGtids": {
        "kind": "AssignGtidsKind",
        "uuid": "Literal",
    },
    "ReplicationFilterRule.DoDb": {
        "databases": "Ident[]",
    },
    "ReplicationFilterRule.IgnoreDb": {
        "databases": "Ident[]",
    },
    "ReplicationFilterRule.DoTable": {
        "tables": "ObjectName[]",
    },
    "ReplicationFilterRule.IgnoreTable": {
        "tables": "ObjectName[]",
    },
    "ReplicationFilterRule.WildDoTable": {
        "patterns": "Literal[]",
    },
    "ReplicationFilterRule.WildIgnoreTable": {
        "patterns": "Literal[]",
    },
    "ReplicationFilterRule.RewriteDb": {
        "pairs": "RewriteDbPair[]",
    },
    "RewriteDbPair": {
        "from": "Ident",
        "to": "Ident",
    },
    "ReplicaThreadOption.Io": {
        "keyword": "IoThreadKeyword",
    },
    "ReplicaUntilCondition.SourceLogFile": {
        "value": "Literal",
    },
    "ReplicaUntilCondition.SourceLogPos": {
        "value": "Literal",
    },
    "ReplicaUntilCondition.RelayLogFile": {
        "value": "Literal",
    },
    "ReplicaUntilCondition.RelayLogPos": {
        "value": "Literal",
    },
    "ReplicaUntilCondition.SqlBeforeGtids": {
        "value": "Literal",
    },
    "ReplicaUntilCondition.SqlAfterGtids": {
        "value": "Literal",
    },
    "GroupReplicationOption.User": {
        "value": "Literal",
    },
    "GroupReplicationOption.Password": {
        "value": "Literal",
    },
    "GroupReplicationOption.DefaultAuth": {
        "value": "Literal",
    },
    "Statement.Query": {
        "query": "Query",
    },
    "Statement.CreateTable": {
        "create": "CreateTable",
    },
    "Statement.AlterTable": {
        "alter": "AlterTable",
    },
    "Statement.Drop": {
        "drop": "DropStatement",
    },
    "Statement.CreateSchema": {
        "schema": "CreateSchema",
    },
    "Statement.CreateView": {
        "view": "CreateView",
    },
    "Statement.RefreshMaterializedView": {
        "refresh": "RefreshMaterializedView",
    },
    "Statement.CreateColocationGroup": {
        "create": "CreateColocationGroup",
    },
    "Statement.DropColocationGroup": {
        "drop": "DropColocationGroup",
    },
    "Statement.AlterView": {
        "alter": "AlterView",
    },
    "Statement.CreateIndex": {
        "index": "CreateIndex",
    },
    "Statement.CreateFunction": {
        "create": "CreateFunction",
    },
    "Statement.CreateProcedure": {
        "create": "CreateProcedure",
    },
    "Statement.AlterRoutine": {
        "alter": "AlterRoutine",
    },
    "Statement.CreateEvent": {
        "create": "CreateEvent",
    },
    "Statement.AlterEvent": {
        "alter": "AlterEvent",
    },
    "Statement.DropEvent": {
        "drop": "DropEvent",
    },
    "Statement.DropDatabase": {
        "drop": "DropDatabase",
    },
    "Statement.DropIndex": {
        "drop": "DropIndexOnTable",
    },
    "Statement.CreateDatabase": {
        "create": "CreateDatabase",
    },
    "Statement.DropRoutine": {
        "kind": "RoutineObjectKind",
        "routines": "RoutineSignature[]",
        "behavior": "DropBehavior",
    },
    "Statement.DropTransform": {
        "drop": "DropTransform",
    },
    "Statement.Truncate": {
        "tables": "ObjectName[]",
        "behavior": "DropBehavior",
    },
    "Statement.CommentOn": {
        "comment": "CommentOnStatement",
    },
    "Statement.Insert": {
        "insert": "Insert",
    },
    "Statement.Update": {
        "update": "Update",
    },
    "Statement.Delete": {
        "delete": "Delete",
    },
    "Statement.Merge": {
        "merge": "Merge",
    },
    "Statement.Transaction": {
        "transaction": "TransactionStatement",
    },
    "Statement.Xa": {
        "xa": "XaStatement",
    },
    "Statement.Session": {
        "session": "SessionStatement",
    },
    "Statement.AccessControl": {
        "access": "AccessControlStatement",
    },
    "Statement.Copy": {
        "copy": "CopyStatement",
    },
    "Statement.CopyInto": {
        "copy": "CopyIntoStatement",
    },
    "Statement.Export": {
        "export": "ExportStatement",
    },
    "Statement.Import": {
        "import": "ImportStatement",
    },
    "Statement.Explain": {
        "explain": "ExplainStatement",
    },
    "Statement.Describe": {
        "describe": "DescribeStatement",
    },
    "Statement.Show": {
        "show": "ShowStatement",
    },
    "Statement.Kill": {
        "kill": "KillStatement",
    },
    "Statement.Handler": {
        "handler": "HandlerStatement",
    },
    "Statement.Install": {
        "install": "InstallStatement",
    },
    "Statement.Uninstall": {
        "uninstall": "UninstallStatement",
    },
    "Statement.Clone": {
        "clone": "CloneStatement",
    },
    "Statement.ImportTable": {
        "import_table": "ImportTableStatement",
    },
    "Statement.Help": {
        "help": "HelpStatement",
    },
    "Statement.Binlog": {
        "binlog": "BinlogStatement",
    },
    "Statement.Pragma": {
        "pragma": "PragmaStatement",
    },
    "Statement.Attach": {
        "attach": "AttachStatement",
    },
    "Statement.Detach": {
        "detach": "DetachStatement",
    },
    "Statement.Checkpoint": {
        "checkpoint": "CheckpointStatement",
    },
    "Statement.Load": {
        "load": "LoadStatement",
    },
    "Statement.LoadData": {
        "load_data": "LoadDataStatement",
    },
    "Statement.UpdateExtensions": {
        "update_extensions": "UpdateExtensionsStatement",
    },
    "Statement.Vacuum": {
        "vacuum": "VacuumStatement",
    },
    "Statement.Reindex": {
        "reindex": "ReindexStatement",
    },
    "Statement.Analyze": {
        "analyze": "AnalyzeStatement",
    },
    "Statement.TableMaintenance": {
        "table_maintenance": "TableMaintenanceStatement",
    },
    "Statement.CacheIndex": {
        "cache_index": "CacheIndexStatement",
    },
    "Statement.LoadIndex": {
        "load_index": "LoadIndexStatement",
    },
    "Statement.Rename": {
        "rename": "RenameStatement",
    },
    "Statement.Flush": {
        "flush": "FlushStatement",
    },
    "Statement.Purge": {
        "purge": "PurgeStatement",
    },
    "Statement.Replication": {
        "replication": "ReplicationStatement",
    },
    "Statement.CreateUser": {
        "create": "CreateUser",
    },
    "Statement.AlterUser": {
        "alter": "AlterUser",
    },
    "Statement.UserRoleList": {
        "statement": "UserRoleList",
    },
    "Statement.Use": {
        "use_statement": "UseStatement",
    },
    "Statement.CreateTrigger": {
        "create": "CreateTrigger",
    },
    "Statement.CreateStoredTrigger": {
        "create": "CreateStoredTrigger",
    },
    "Statement.CreateMacro": {
        "create": "CreateMacro",
    },
    "Statement.CreateSecret": {
        "create": "CreateSecret",
    },
    "Statement.DropSecret": {
        "drop": "DropSecretStmt",
    },
    "Statement.CreateType": {
        "create": "CreateType",
    },
    "Statement.CreateVirtualTable": {
        "create": "CreateVirtualTable",
    },
    "Statement.CreateSequence": {
        "create": "CreateSequence",
    },
    "Statement.CreateExtension": {
        "create": "CreateExtension",
    },
    "Statement.AlterExtension": {
        "alter": "AlterExtension",
    },
    "Statement.CreateTablespace": {
        "create": "CreateTablespace",
    },
    "Statement.AlterTablespace": {
        "alter": "AlterTablespace",
    },
    "Statement.DropTablespace": {
        "drop": "DropTablespace",
    },
    "Statement.CreateLogfileGroup": {
        "create": "CreateLogfileGroup",
    },
    "Statement.AlterLogfileGroup": {
        "alter": "AlterLogfileGroup",
    },
    "Statement.DropLogfileGroup": {
        "drop": "DropLogfileGroup",
    },
    "Statement.AlterObjectDepends": {
        "alter": "AlterObjectDepends",
    },
    "Statement.AlterSystem": {
        "alter": "AlterSystem",
    },
    "Statement.AlterDatabase": {
        "alter": "AlterDatabase",
    },
    "Statement.AlterDatabaseOptions": {
        "alter": "AlterDatabaseOptions",
    },
    "Statement.CreateServer": {
        "create": "CreateServer",
    },
    "Statement.AlterServer": {
        "alter": "AlterServer",
    },
    "Statement.DropServer": {
        "drop": "DropServer",
    },
    "Statement.AlterInstance": {
        "alter": "AlterInstance",
    },
    "Statement.CreateSpatialReferenceSystem": {
        "create": "CreateSpatialReferenceSystem",
    },
    "Statement.DropSpatialReferenceSystem": {
        "drop": "DropSpatialReferenceSystem",
    },
    "Statement.CreateResourceGroup": {
        "create": "CreateResourceGroup",
    },
    "Statement.AlterResourceGroup": {
        "alter": "AlterResourceGroup",
    },
    "Statement.DropResourceGroup": {
        "drop": "DropResourceGroup",
    },
    "Statement.AlterSequence": {
        "alter": "AlterSequence",
    },
    "Statement.AlterObjectSchema": {
        "alter": "AlterObjectSchema",
    },
    "Statement.Pivot": {
        "pivot": "Pivot",
    },
    "Statement.Unpivot": {
        "unpivot": "Unpivot",
    },
    "Statement.ShowRef": {
        "show": "ShowRef",
    },
    "Statement.Prepare": {
        "prepare": "PrepareStatement",
    },
    "Statement.Execute": {
        "execute": "ExecuteStatement",
    },
    "Statement.PrepareFrom": {
        "prepare_from": "PrepareFromStatement",
    },
    "Statement.ExecuteUsing": {
        "execute_using": "ExecuteUsingStatement",
    },
    "Statement.Deallocate": {
        "deallocate": "DeallocateStatement",
    },
    "Statement.Call": {
        "call": "CallStatement",
    },
    "Statement.Do": {
        "do_block": "DoStatement",
    },
    "Statement.DoExpressions": {
        "do_expressions": "DoExpressionsStatement",
    },
    "Statement.LockTables": {
        "lock_tables": "LockTablesStatement",
    },
    "Statement.UnlockTables": {
        "unlock_tables": "UnlockTablesStatement",
    },
    "Statement.InstanceLock": {
        "instance_lock": "InstanceLockStatement",
    },
    "Statement.Compound": {
        "compound": "CompoundStatement",
    },
    "Statement.If": {
        "if_statement": "IfStatement",
    },
    "Statement.Case": {
        "case_statement": "CaseStatement",
    },
    "Statement.Loop": {
        "loop_statement": "LoopStatement",
    },
    "Statement.While": {
        "while_statement": "WhileStatement",
    },
    "Statement.Repeat": {
        "repeat": "RepeatStatement",
    },
    "Statement.Leave": {
        "leave": "LeaveStatement",
    },
    "Statement.Iterate": {
        "iterate": "IterateStatement",
    },
    "Statement.Return": {
        "return_statement": "ReturnStatement",
    },
    "Statement.OpenCursor": {
        "open": "OpenCursorStatement",
    },
    "Statement.FetchCursor": {
        "fetch": "FetchCursorStatement",
    },
    "Statement.CloseCursor": {
        "close": "CloseCursorStatement",
    },
    "Statement.Signal": {
        "signal": "SignalStatement",
    },
    "Statement.Resignal": {
        "resignal": "SignalStatement",
    },
    "Statement.GetDiagnostics": {
        "get_diagnostics": "GetDiagnosticsStatement",
    },
    "Statement.Other": {
        "ext": "NoExt",
    },
    "CompoundStatement": {
        "label": "Ident",
        "declarations": "Declaration[]",
        "body": "Statement[]",
        "end_label": "Ident",
    },
    "Declaration.Variable": {
        "names": "Ident[]",
        "data_type": "DataType",
        "default": "Expr",
    },
    "Declaration.Condition": {
        "name": "Ident",
        "value": "ConditionValue",
    },
    "Declaration.Cursor": {
        "name": "Ident",
        "query": "Query",
    },
    "Declaration.Handler": {
        "action": "HandlerAction",
        "conditions": "HandlerCondition[]",
        "body": "Statement",
    },
    "ConditionValue.SqlState": {
        "sqlstate": "Literal",
    },
    "ConditionValue.ErrorCode": {
        "code": "Literal",
    },
    "ConditionValue.ConditionName": {
        "name": "Ident",
    },
    "HandlerCondition.SqlState": {
        "sqlstate": "Literal",
    },
    "HandlerCondition.ErrorCode": {
        "code": "Literal",
    },
    "HandlerCondition.ConditionName": {
        "name": "Ident",
    },
    "IfStatement": {
        "branches": "ConditionalBranch[]",
        "else_body": "Statement[]",
    },
    "ConditionalBranch": {
        "guard": "Expr",
        "body": "Statement[]",
    },
    "CaseStatement": {
        "operand": "Expr",
        "when_branches": "ConditionalBranch[]",
        "else_body": "Statement[]",
    },
    "LoopStatement": {
        "label": "Ident",
        "body": "Statement[]",
        "end_label": "Ident",
    },
    "WhileStatement": {
        "label": "Ident",
        "condition": "Expr",
        "body": "Statement[]",
        "end_label": "Ident",
    },
    "RepeatStatement": {
        "label": "Ident",
        "body": "Statement[]",
        "condition": "Expr",
        "end_label": "Ident",
    },
    "LeaveStatement": {
        "label": "Ident",
    },
    "IterateStatement": {
        "label": "Ident",
    },
    "ReturnStatement": {
        "value": "Expr",
    },
    "OpenCursorStatement": {
        "cursor": "Ident",
    },
    "CloseCursorStatement": {
        "cursor": "Ident",
    },
    "FetchCursorStatement": {
        "cursor": "Ident",
        "targets": "Ident[]",
    },
    "SignalStatement": {
        "condition": "ConditionValue",
        "set_items": "SignalItem[]",
    },
    "SignalItem": {
        "name": "SignalItemName",
        "value": "Expr",
    },
    "GetDiagnosticsStatement": {
        "area": "DiagnosticsArea",
        "info": "DiagnosticsInfo",
    },
    "DiagnosticsInfo.Statement": {
        "items": "StatementInfoItem[]",
    },
    "DiagnosticsInfo.Condition": {
        "number": "Expr",
        "items": "ConditionInfoItem[]",
    },
    "StatementInfoItem": {
        "target": "Expr",
        "name": "StatementInfoItemName",
    },
    "ConditionInfoItem": {
        "target": "Expr",
        "name": "ConditionInfoItemName",
    },
    "TransactionStatement.Begin": {
        "syntax": "TransactionStart",
        "mode": "TransactionModeKind",
        "block": "TransactionBlockKeyword",
        "modes": "TransactionMode[]",
    },
    "TransactionStatement.Commit": {
        "block": "TransactionBlockKeyword",
    },
    "TransactionStatement.Rollback": {
        "block": "TransactionBlockKeyword",
        "to_savepoint": "Ident",
    },
    "TransactionStatement.Savepoint": {
        "name": "Ident",
    },
    "TransactionStatement.Release": {
        "savepoint": "Ident",
    },
    "TransactionStatement.SetCharacteristics": {
        "modes": "TransactionMode[]",
    },
    "TransactionMode.IsolationLevel": {
        "level": "IsolationLevel",
    },
    "TransactionMode.AccessMode": {
        "access": "TransactionAccessMode",
    },
    "XaStatement.Start": {
        "keyword": "XaStartKeyword",
        "xid": "Xid",
        "association": "XaAssociation",
    },
    "XaStatement.End": {
        "xid": "Xid",
        "suspend": "XaSuspend",
    },
    "XaStatement.Prepare": {
        "xid": "Xid",
    },
    "XaStatement.Commit": {
        "xid": "Xid",
    },
    "XaStatement.Rollback": {
        "xid": "Xid",
    },
    "Xid": {
        "gtrid": "Literal",
        "bqual": "Literal",
        "format_id": "Literal",
    },
    "DataType.Boolean": {
        "spelling": "BooleanTypeName",
    },
    "DataType.Integer": {
        "spelling": "IntegerTypeName",
    },
    "DataType.Decimal": {
        "spelling": "DecimalTypeName",
    },
    "DataType.Double": {
        "spelling": "DoubleTypeName",
    },
    "DataType.Text": {
        "spelling": "TextTypeName",
        "charset": "CharsetAnnotation",
    },
    "DataType.Blob": {
        "spelling": "BlobTypeName",
    },
    "DataType.Character": {
        "spelling": "CharacterTypeName",
        "charset": "CharsetAnnotation",
    },
    "DataType.Binary": {
        "spelling": "BinaryTypeName",
    },
    "DataType.Time": {
        "spelling": "TimeTypeName",
        "time_zone": "TimeZone",
    },
    "DataType.Timestamp": {
        "spelling": "TimestampTypeName",
        "time_zone": "TimeZone",
    },
    "DataType.Interval": {
        "fields": "IntervalFields",
    },
    "DataType.Enum": {
        "values": "Literal[]",
        "charset": "CharsetAnnotation",
    },
    "DataType.Set": {
        "values": "Literal[]",
        "charset": "CharsetAnnotation",
    },
    "DataType.NumericModifier": {
        "element": "DataType",
        "signedness": "Signedness",
    },
    "DataType.Array": {
        "element": "DataType",
        "spelling": "ArrayTypeSpelling",
    },
    "DataType.Struct": {
        "fields": "StructTypeField[]",
        "spelling": "StructTypeSpelling",
    },
    "DataType.Union": {
        "members": "StructTypeField[]",
    },
    "DataType.Map": {
        "key": "DataType",
        "value": "DataType",
    },
    "DataType.Wrapped": {
        "kind": "WrappedTypeKind",
        "inner": "DataType",
    },
    "DataType.DateTime64": {
        "timezone": "Literal",
    },
    "DataType.Nested": {
        "fields": "StructTypeField[]",
    },
    "DataType.FixedWidthInt": {
        "width": "IntWidth",
    },
    "DataType.UserDefined": {
        "name": "ObjectName",
        "modifiers": "Literal[]",
    },
    "DataType.Liberal": {
        "words": "Ident[]",
    },
    "DataType.Other": {
        "ext": "NoExt",
    },
    "StructTypeField": {
        "name": "Ident",
        "ty": "DataType",
    },
    "CharsetAnnotation": {
        "charset": "Charset",
        "name": "Ident",
    },
    "CopyStatement": {
        "source": "CopySource",
        "direction": "CopyDirection",
        "target": "CopyTarget",
        "delimiters": "Literal",
        "options": "CopyOption[]",
        "filter": "Expr",
    },
    "CopySource.Table": {
        "table": "ObjectName",
        "columns": "Ident[]",
    },
    "CopySource.Query": {
        "query": "Statement",
    },
    "CopyTarget.File": {
        "path": "Literal",
    },
    "CopyTarget.Program": {
        "command": "Literal",
    },
    "CopyOption": {
        "name": "Ident",
        "value": "CopyOptionValue",
    },
    "CopyOptionValue.Word": {
        "word": "Ident",
    },
    "CopyOptionValue.String": {
        "value": "Literal",
    },
    "CopyOptionValue.Number": {
        "value": "Literal",
    },
    "CopyOptionValue.List": {
        "values": "CopyOptionValue[]",
    },
    "CopyOptionValue.Force": {
        "kind": "ForceKind",
        "columns": "Ident[]",
    },
    "CopyOptionValue.OptionList": {
        "options": "CopyOption[]",
    },
    "CopyIntoStatement": {
        "target": "CopyIntoTarget",
        "source": "CopyIntoSource",
        "options": "CopyOption[]",
    },
    "CopyIntoTarget.Table": {
        "table": "ObjectName",
        "columns": "Ident[]",
    },
    "CopyIntoTarget.External": {
        "location": "Literal",
    },
    "CopyIntoTarget.Stage": {
        "reference": "Ident",
    },
    "CopyIntoSource.Table": {
        "table": "ObjectName",
    },
    "CopyIntoSource.External": {
        "location": "Literal",
    },
    "CopyIntoSource.Stage": {
        "reference": "Ident",
    },
    "CopyIntoSource.Query": {
        "query": "Statement",
    },
    "ExportStatement": {
        "database": "Ident",
        "path": "Literal",
        "options": "CopyOption[]",
    },
    "ImportStatement": {
        "path": "Literal",
    },
    "ExplainStatement": {
        "spelling": "ExplainKeyword",
        "options": "ExplainOption[]",
        "statement": "Statement",
    },
    "ExplainOption.Analyze": {
        "value": "Ident",
    },
    "ExplainOption.Verbose": {
        "value": "Ident",
    },
    "ExplainOption.Format": {
        "format": "ExplainFormat",
    },
    "ExplainOption.Other": {
        "name": "Ident",
        "value": "Ident",
    },
    "DescribeStatement": {
        "keyword": "ExplainKeyword",
        "table": "ObjectName",
        "column": "DescribeColumn",
    },
    "DescribeColumn.Name": {
        "name": "Ident",
    },
    "DescribeColumn.Wild": {
        "pattern": "Literal",
    },
    "KillStatement": {
        "target": "KillTarget",
        "id": "Expr",
    },
    "InstallStatement.Plugin": {
        "name": "Ident",
        "soname": "Literal",
    },
    "InstallStatement.Component": {
        "urns": "Literal[]",
        "set": "InstallComponentSetElement[]",
    },
    "UninstallStatement.Plugin": {
        "name": "Ident",
    },
    "UninstallStatement.Component": {
        "urns": "Literal[]",
    },
    "InstallComponentSetElement": {
        "scope": "InstallComponentSetScope",
        "name": "ObjectName",
        "assignment": "SetAssignment",
        "value": "InstallComponentSetValue",
    },
    "InstallComponentSetValue.Expr": {
        "expr": "Expr",
    },
    "HandlerStatement": {
        "table": "ObjectName",
        "operation": "HandlerOperation",
    },
    "HandlerOperation.Open": {
        "alias": "Ident",
    },
    "HandlerOperation.Read": {
        "selector": "HandlerReadSelector",
        "selection": "Expr",
        "limit": "Limit",
    },
    "HandlerReadSelector.Scan": {
        "direction": "HandlerScanDirection",
    },
    "HandlerReadSelector.Index": {
        "index": "Ident",
        "direction": "HandlerIndexDirection",
    },
    "HandlerReadSelector.Key": {
        "index": "Ident",
        "comparison": "HandlerKeyComparison",
        "key": "ValuesItem[]",
    },
    "CloneStatement.Local": {
        "data_directory": "CloneDataDirectory",
    },
    "CloneStatement.Instance": {
        "source": "AccountName",
        "port": "Literal",
        "password": "Literal",
        "data_directory": "CloneDataDirectory",
        "ssl": "CloneSsl",
    },
    "CloneDataDirectory": {
        "path": "Literal",
    },
    "ImportTableStatement": {
        "files": "Literal[]",
    },
    "HelpStatement": {
        "topic": "Ident",
    },
    "BinlogStatement": {
        "event": "Literal",
    },
    "PragmaStatement": {
        "name": "ObjectName",
        "value": "SetParameterValue",
    },
    "AttachStatement": {
        "target": "Expr",
        "schema": "Ident",
    },
    "DetachStatement": {
        "schema": "Ident",
    },
    "CheckpointStatement": {
        "database": "Ident",
    },
    "LoadStatement": {
        "target": "LoadTarget",
    },
    "LoadTarget.Name": {
        "name": "Ident",
    },
    "LoadTarget.Path": {
        "path": "Literal",
    },
    "UpdateExtensionsStatement": {
        "extensions": "Ident[]",
    },
    "VacuumStatement": {
        "schema": "Ident",
        "into": "Expr",
        "analyze": "VacuumAnalyze",
        "table": "ObjectName",
        "columns": "Ident[]",
    },
    "ReindexStatement": {
        "target": "ObjectName",
    },
    "AnalyzeStatement": {
        "target": "ObjectName",
        "columns": "Ident[]",
    },
    "TableMaintenanceStatement": {
        "kind": "TableMaintenanceKind",
        "table_keyword": "TableKeyword",
        "tables": "ObjectName[]",
    },
    "TableMaintenanceKind.Analyze": {
        "no_write_to_binlog": "NoWriteToBinlog",
        "histogram": "AnalyzeHistogram",
    },
    "TableMaintenanceKind.Check": {
        "options": "CheckTableOption[]",
    },
    "TableMaintenanceKind.Checksum": {
        "option": "ChecksumTableOption",
    },
    "TableMaintenanceKind.Optimize": {
        "no_write_to_binlog": "NoWriteToBinlog",
    },
    "TableMaintenanceKind.Repair": {
        "no_write_to_binlog": "NoWriteToBinlog",
        "options": "RepairTableOption[]",
    },
    "AnalyzeHistogram.Update": {
        "columns": "Ident[]",
        "buckets": "Literal",
    },
    "AnalyzeHistogram.Drop": {
        "columns": "Ident[]",
    },
    "CacheIndexStatement": {
        "targets": "CacheIndexTargets",
        "cache": "KeyCacheName",
    },
    "CacheIndexTargets.Tables": {
        "tables": "CacheIndexTable[]",
    },
    "CacheIndexTargets.Partition": {
        "table": "ObjectName",
        "partition": "PartitionSelection",
        "keys": "CacheIndexKeyList",
    },
    "CacheIndexTable": {
        "table": "ObjectName",
        "keys": "CacheIndexKeyList",
    },
    "LoadIndexStatement": {
        "targets": "LoadIndexTargets",
    },
    "LoadIndexTargets.Tables": {
        "tables": "LoadIndexTable[]",
    },
    "LoadIndexTargets.Partition": {
        "table": "ObjectName",
        "partition": "PartitionSelection",
        "keys": "CacheIndexKeyList",
    },
    "LoadIndexTable": {
        "table": "ObjectName",
        "keys": "CacheIndexKeyList",
    },
    "CacheIndexKeyList": {
        "keyword": "CacheIndexKeyword",
        "keys": "Ident[]",
    },
    "KeyCacheName.Named": {
        "name": "Ident",
    },
    "PartitionSelection.Names": {
        "names": "Ident[]",
    },
    "RenameStatement.Table": {
        "table_keyword": "TableKeyword",
        "renames": "TableRename[]",
    },
    "RenameStatement.User": {
        "renames": "UserRename[]",
    },
    "TableRename": {
        "from": "ObjectName",
        "to": "ObjectName",
    },
    "UserRename": {
        "from": "AccountName",
        "to": "AccountName",
    },
    "AccountName.Account": {
        "user": "Ident",
        "host": "Ident",
    },
    "FlushStatement": {
        "no_write_to_binlog": "NoWriteToBinlog",
        "target": "FlushTarget",
    },
    "FlushTarget.Tables": {
        "table_keyword": "TableKeyword",
        "tables": "ObjectName[]",
        "lock": "FlushTablesLock",
    },
    "FlushTarget.Options": {
        "options": "FlushOption[]",
    },
    "FlushOption.RelayLogs": {
        "channel": "Literal",
    },
    "PurgeStatement": {
        "target": "PurgeTarget",
    },
    "PurgeTarget.To": {
        "log": "Literal",
    },
    "PurgeTarget.Before": {
        "datetime": "Expr",
    },
    "UseStatement": {
        "name": "ObjectName",
    },
    "PrepareStatement": {
        "name": "Ident",
        "parameter_types": "DataType[]",
        "statement": "Statement",
    },
    "PrepareFromStatement": {
        "name": "Ident",
        "source": "PrepareSource",
    },
    "PrepareSource.Text": {
        "source": "Literal",
    },
    "PrepareSource.Variable": {
        "name": "Ident",
    },
    "ExecuteStatement": {
        "name": "Ident",
        "args": "Expr[]",
    },
    "ExecuteUsingStatement": {
        "name": "Ident",
        "using": "Ident[]",
    },
    "CallStatement": {
        "name": "ObjectName",
        "args": "Expr[]",
    },
    "DeallocateStatement": {
        "keyword": "DeallocateKeyword",
        "name": "Ident",
    },
    "DoStatement": {
        "args": "DoArg[]",
    },
    "DoArg.Body": {
        "body": "Literal",
    },
    "DoArg.Language": {
        "name": "LanguageName",
    },
    "LanguageName.Word": {
        "word": "Ident",
    },
    "LanguageName.String": {
        "value": "Literal",
    },
    "DoExpressionsStatement": {
        "items": "SelectItem[]",
    },
    "LockTablesStatement": {
        "tables": "TableLock[]",
    },
    "TableLock": {
        "name": "ObjectName",
        "alias": "Ident",
        "kind": "TableLockKind",
    },
    "LoadDataStatement": {
        "format": "LoadDataFormat",
        "concurrency": "LoadDataConcurrency",
        "file": "Literal",
        "on_duplicate": "LoadDataDuplicate",
        "table": "ObjectName",
        "partitions": "Ident[]",
        "charset": "Ident",
        "rows_identified_by": "Literal",
        "fields": "LoadDataFields",
        "lines": "LoadDataLines",
        "ignore_rows": "LoadDataIgnoreRows",
        "columns": "LoadDataFieldOrVar[]",
        "set": "UpdateAssignment[]",
    },
    "LoadDataFields": {
        "spelling": "LoadFieldsSpelling",
        "terminated_by": "Literal",
        "enclosed_by": "LoadDataEnclosed",
        "escaped_by": "Literal",
    },
    "LoadDataEnclosed": {
        "value": "Literal",
    },
    "LoadDataLines": {
        "starting_by": "Literal",
        "terminated_by": "Literal",
    },
    "LoadDataIgnoreRows": {
        "count": "Literal",
        "unit": "LoadDataIgnoreUnit",
    },
    "LoadDataFieldOrVar.Column": {
        "name": "Ident",
    },
    "LoadDataFieldOrVar.Variable": {
        "name": "Ident",
    },
    "ShowStatement": {
        "target": "ShowTarget",
    },
    "ShowTarget.Tables": {
        "from": "ShowFrom",
        "filter": "ShowFilter",
    },
    "ShowTarget.Columns": {
        "spelling": "ShowColumnsSpelling",
        "table": "ShowFrom",
        "database": "ShowFrom",
        "filter": "ShowFilter",
    },
    "ShowTarget.Create": {
        "kind": "ShowCreateKind",
        "name": "ObjectName",
    },
    "ShowTarget.Functions": {
        "kind": "ShowFunctionsScope",
        "from": "ShowFrom",
        "filter": "ShowFunctionsFilter",
    },
    "ShowTarget.RoutineStatus": {
        "kind": "ShowRoutineKind",
        "filter": "ShowFilter",
    },
    "ShowTarget.Listing": {
        "kind": "ShowListing",
        "from": "ShowFrom",
        "filter": "ShowFilter",
    },
    "ShowTarget.Bare": {
        "kind": "ShowBare",
    },
    "ShowTarget.Grants": {
        "user": "AccountName",
        "using_roles": "AccountName[]",
    },
    "ShowTarget.CreateUser": {
        "user": "AccountName",
    },
    "ShowTarget.Profile": {
        "types": "ShowProfileType[]",
        "query": "Literal",
        "limit": "ShowLimit",
    },
    "ShowTarget.LogEvents": {
        "log_name": "Literal",
        "position": "Literal",
        "limit": "ShowLimit",
        "channel": "Literal",
    },
    "ShowTarget.Index": {
        "spelling": "ShowIndexSpelling",
        "table": "ShowFrom",
        "database": "ShowFrom",
        "filter": "ShowFilter",
    },
    "ShowTarget.Engine": {
        "engine": "Ident",
        "artifact": "ShowEngineArtifact",
    },
    "ShowTarget.ReplicaStatus": {
        "channel": "Literal",
    },
    "ShowTarget.Diagnostics": {
        "kind": "ShowDiagnosticKind",
        "limit": "ShowLimit",
    },
    "ShowTarget.RoutineCode": {
        "kind": "ShowRoutineKind",
        "name": "ObjectName",
    },
    "ShowFunctionsFilter.Name": {
        "name": "ObjectName",
    },
    "ShowFunctionsFilter.Regex": {
        "pattern": "Literal",
    },
    "ShowFrom": {
        "keyword": "ShowFromKeyword",
        "name": "ObjectName",
    },
    "ShowFilter.Like": {
        "pattern": "Literal",
    },
    "ShowFilter.Where": {
        "predicate": "Expr",
    },
    "ShowListing.Status": {
        "scope": "ShowScope",
    },
    "ShowListing.Variables": {
        "scope": "ShowScope",
    },
    "ShowLimit": {
        "offset": "Literal",
        "row_count": "Literal",
    },
    "WindowSpec.Named": {
        "name": "Ident",
    },
    "WindowSpec.Inline": {
        "definition": "WindowDefinition",
    },
    "WindowDefinition": {
        "existing": "Ident",
        "partition_by": "Expr[]",
        "order_by": "OrderByExpr[]",
        "frame": "WindowFrame",
    },
    "WindowFrame": {
        "units": "WindowFrameUnits",
        "start": "WindowFrameBound",
        "end": "WindowFrameBound",
        "exclusion": "WindowFrameExclusion",
    },
    "WindowFrameBound.Preceding": {
        "offset": "Expr",
    },
    "WindowFrameBound.Following": {
        "offset": "Expr",
    },
    "NamedWindow": {
        "name": "Ident",
        "definition": "WindowDefinition",
    },
}
