# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Moderately AI Inc.

from __future__ import annotations

from collections.abc import Iterator, Mapping
from dataclasses import dataclass
from typing import Any, Generic, Optional, TypeVar, Union

from .ast import AstNodeJson, IdentJson, StatementJson
from ._types import ParseDocumentJson, RecoveredDocumentJson
from ._native import NativeDocument, NativeRecoveredDocument

JsonDict = dict[str, Any]
_TRaw = TypeVar("_TRaw")
_TDialect = TypeVar("_TDialect", bound=str, covariant=True)

@dataclass(frozen=True)
class SourceLocation:
    line: int
    byte_column: int
    char_column: int
    utf16_column: int

@dataclass(frozen=True)
class Span:
    start: int
    end: int

class Document(Mapping[str, Any], Generic[_TDialect]):
    def __init__(self, raw: Optional[JsonDict] = None, *, native: Optional[Union[NativeDocument, NativeRecoveredDocument]] = None) -> None: ...
    @property
    def raw(self) -> ParseDocumentJson: ...
    @property
    def source(self) -> str: ...
    @property
    def dialect(self) -> _TDialect: ...
    @property
    def statements(self) -> list[Node[StatementJson]]: ...
    @property
    def trivia(self) -> list[Trivia]: ...
    @property
    def errors(self) -> list[Diagnostic]: ...
    def resolve_symbol(self, symbol: int) -> str: ...
    def source_text(self, span: Union[Span, Mapping[str, Any]]) -> str: ...
    def location(self, offset: int) -> SourceLocation: ...
    def walk(self) -> Iterator[Node]: ...
    def find_all(self, kind: Union[str, type[Node]]) -> Iterator[Node]: ...
    def to_dict(self) -> ParseDocumentJson: ...
    def to_json(self) -> str: ...
    def to_sql(self, *, dialect: Optional[str] = None, mode: str = "canonical") -> str: ...
    def __getitem__(self, key: str) -> Any: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...

class RecoveredDocument(Document[_TDialect], Generic[_TDialect]):
    @property
    def raw(self) -> RecoveredDocumentJson: ...
    def to_dict(self) -> RecoveredDocumentJson: ...

class Node(Generic[_TRaw]):
    def __init__(self, raw: JsonDict, document: Document, type_name: Optional[str] = None) -> None: ...
    document: Document[str]
    type_name: Optional[str]
    kind: str
    @property
    def raw(self) -> _TRaw: ...
    @property
    def span(self) -> Optional[Span]: ...
    @property
    def node_id(self) -> Optional[int]: ...
    @property
    def is_renderable(self) -> bool: ...
    def source_text(self) -> Optional[str]: ...
    def location(self) -> Optional[SourceLocation]: ...
    def children(self) -> list[Node[AstNodeJson]]: ...
    def walk(self) -> Iterator[Node[AstNodeJson]]: ...
    def find_all(self, kind: Union[str, type[Node[Any]]]) -> Iterator[Node[AstNodeJson]]: ...
    def to_dict(self) -> _TRaw: ...
    def to_sql(self, *, dialect: Optional[str] = None, mode: str = "canonical") -> str: ...
    def __getattr__(self, name: str) -> Any: ...
    def __getitem__(self, key: str) -> Any: ...

class Ident(Node[IdentJson]):
    def __init__(self, raw: JsonDict, document: Document) -> None: ...
    @property
    def symbol(self) -> int: ...
    @property
    def text(self) -> str: ...
    @property
    def quote(self) -> str: ...

class ObjectName:
    def __init__(self, raw: list[Any], document: Document) -> None: ...
    document: Document
    parts: list[Ident]
    @property
    def text(self) -> str: ...
    def to_dict(self) -> list[Any]: ...
    def __iter__(self) -> Iterator[Ident]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Ident: ...

class Diagnostic(Mapping[str, Any]):
    def __init__(self, raw: JsonDict, document: Document) -> None: ...
    raw: JsonDict
    document: Document
    @property
    def message(self) -> str: ...
    @property
    def kind(self) -> str: ...
    @property
    def span(self) -> Optional[Span]: ...
    def source_text(self) -> Optional[str]: ...
    def location(self) -> Optional[SourceLocation]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...

class Trivia(Mapping[str, Any]):
    def __init__(self, raw: JsonDict, document: Document) -> None: ...
    raw: JsonDict
    document: Document
    @property
    def kind(self) -> str: ...
    @property
    def span(self) -> Span: ...
    @property
    def text(self) -> str: ...
    def location(self) -> SourceLocation: ...
    def __getitem__(self, key: str) -> Any: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...

def document_from_json(text: str, *, recovered: bool = False) -> Document: ...
def document_from_native(native: Union[NativeDocument, NativeRecoveredDocument], *, recovered: bool = False) -> Document: ...
