# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Moderately AI Inc.

from typing import Optional

__version__: str
__schema_version__: int
__all__ = [
    "__schema_version__", "__version__", "format", "parse", "parse_recovering",
    "render_document", "render_fragment", "render_sql", "supported_dialects",
    "tokenize", "transpile",
]

def parse(sql: str, dialect: str = "ansi", recursion_limit: Optional[int] = None, capture_trivia: bool = False, parse_float_as_decimal: bool = False) -> str: ...
def parse_recovering(sql: str, dialect: str = "ansi", recursion_limit: Optional[int] = None, capture_trivia: bool = False, parse_float_as_decimal: bool = False) -> str: ...
def supported_dialects() -> str: ...
def tokenize(sql: str, dialect: str = "ansi", include_trivia: bool = False) -> str: ...
def render_document(document_json: str, dialect: str = "ansi", mode: str = "canonical") -> str: ...
def render_fragment(document_json: str, node_id: int, dialect: str = "ansi", mode: str = "canonical") -> str: ...
def render_sql(sql: str, dialect: str = "ansi", mode: str = "canonical", recursion_limit: Optional[int] = None) -> str: ...
def transpile(sql: str, source_dialect: str = "ansi", target_dialect: str = "ansi", recursion_limit: Optional[int] = None) -> str: ...
def format(sql: str, dialect: str = "ansi", indent_width: int = 2, max_line_length: int = 80, keyword_case: str = "upper") -> str: ...
