# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Moderately AI Inc.

from typing import Optional, final

__version__: str
__schema_version__: int
__all__ = [
    "__schema_version__", "__version__", "format", "parse", "parse_document", "parse_recovering",
    "parse_recovering_document", "NativeDocument", "NativeRecoveredDocument",
    "render_document", "render_fragment", "render_sql", "supported_dialects",
    "tokenize", "transpile",
]

@final
class NativeDocument:
    @property
    def source(self) -> str: ...
    @property
    def dialect(self) -> str: ...
    def to_json(self) -> str: ...
    def render(self, dialect: str, mode: str = "canonical") -> str: ...
    def render_fragment(self, node_id: int, dialect: str, mode: str = "canonical") -> str: ...

@final
class NativeRecoveredDocument:
    @property
    def source(self) -> str: ...
    @property
    def dialect(self) -> str: ...
    def to_json(self) -> str: ...
    def render(self, dialect: str, mode: str = "canonical") -> str: ...
    def render_fragment(self, node_id: int, dialect: str, mode: str = "canonical") -> str: ...

def parse(sql: str, dialect: str = "ansi", recursion_limit: Optional[int] = None, capture_trivia: bool = False, parse_float_as_decimal: bool = False) -> str: ...
def parse_document(sql: str, dialect: str = "ansi", recursion_limit: Optional[int] = None, capture_trivia: bool = False, parse_float_as_decimal: bool = False) -> NativeDocument: ...
def parse_recovering(sql: str, dialect: str = "ansi", recursion_limit: Optional[int] = None, capture_trivia: bool = False, parse_float_as_decimal: bool = False) -> str: ...
def parse_recovering_document(sql: str, dialect: str = "ansi", recursion_limit: Optional[int] = None, capture_trivia: bool = False, parse_float_as_decimal: bool = False) -> NativeRecoveredDocument: ...
def supported_dialects() -> str: ...
def tokenize(sql: str, dialect: str = "ansi", include_trivia: bool = False) -> str: ...
def render_document(document_json: str, dialect: str = "ansi", mode: str = "canonical") -> str: ...
def render_fragment(document_json: str, node_id: int, dialect: str = "ansi", mode: str = "canonical") -> str: ...
def render_sql(sql: str, dialect: str = "ansi", mode: str = "canonical", recursion_limit: Optional[int] = None) -> str: ...
def transpile(sql: str, source_dialect: str = "ansi", target_dialect: str = "ansi", recursion_limit: Optional[int] = None) -> str: ...
def format(sql: str, dialect: str = "ansi", indent_width: int = 2, max_line_length: int = 80, keyword_case: str = "upper") -> str: ...
