// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Moderately AI Inc.

//! Emits the two keyword lookups the ADR-0004 `phf` comparison measures — but only
//! under `--features phf-compare`.
//!
//! Both are written to `OUT_DIR` and `include!`d by
//! `benches/keyword_lookup_ref/mod.rs`:
//!
//! - `generated_keywords.rs` — the REAL dependency-free generated lookup over the
//!   full ANSI/PostgreSQL inventory, rendered by the production `squonk-sourcegen`
//!   codegen, so the bench exercises the actual generated path (ADR-0004), not a
//!   re-implementation.
//! - `phf_keywords.rs` — a `phf` perfect-hash map over the SAME inventory.
//!
//! Without the feature this script does nothing and its codegen build-deps are not
//! compiled, so the default bench build (and the `cargo nextest` / `clippy` gates)
//! stay free of both `phf` and the codegen toolchain (ADR-0017).

fn main() {
    #[cfg(feature = "phf-compare")]
    generate::emit();
}

#[cfg(feature = "phf-compare")]
mod generate {
    use std::env;
    use std::fs;
    use std::io::Write as _;
    use std::path::Path;

    pub fn emit() {
        let out_dir = env::var("OUT_DIR").expect("cargo sets OUT_DIR for build scripts");
        let out = Path::new(&out_dir);

        // The exact production codegen path (ADR-0004), unformatted: the compiler
        // does not care about layout, and skipping the format pass keeps this build
        // script from shelling out to an external `rustfmt`.
        //
        // The codegen prepends a file header (a `//!` doc block + an inner
        // `#![allow(clippy::all)]`). Inner attributes are illegal where this is
        // `include!`d inside a child `mod`, so drop the header — slice from the
        // first item, the `#[repr(u16)]` on the enum — and re-apply the clippy
        // allow as an outer attribute at the include site instead.
        let generated = squonk_sourcegen::generate_keywords_unformatted();
        let body_start = generated
            .find("#[repr(u16)]")
            .expect("generated keyword module starts the enum with #[repr(u16)]");
        fs::write(out.join("generated_keywords.rs"), &generated[body_start..])
            .expect("write generated_keywords.rs");

        emit_phf_map(out);

        // Rebuild both lookups when the source inventory changes.
        let data = workspace_keyword_data();
        for csv in ["ansi_keywords.csv", "postgres_keywords.csv"] {
            println!("cargo:rerun-if-changed={}", data.join(csv).display());
        }
    }

    /// Render `phf_keywords.rs`: a `phf::Map` keyed on the lower-case spelling
    /// bytes, so the lookup wrapper can hash the same lowered buffer the generated
    /// path binary-searches — a fair, allocation-free head-to-head.
    fn emit_phf_map(out: &Path) {
        // `phf_codegen` keys must outlive the builder and implement `FmtConst`,
        // which rules out owned `Vec<u8>`; keep the owned spellings in `entries`
        // and hand the builder borrowed `&[u8]` slices into them.
        let entries: Vec<(Vec<u8>, String)> = squonk_sourcegen::keyword_inventory()
            .into_iter()
            .map(|(spelling, variant)| (spelling.into_bytes(), variant))
            .collect();
        let max_len = entries.iter().map(|(key, _)| key.len()).max().unwrap_or(0);

        let mut map = phf_codegen::Map::<&[u8]>::new();
        for (key, variant) in &entries {
            map.entry(key.as_slice(), &format!("Keyword::{variant}"));
        }

        let mut rendered = Vec::new();
        write!(
            rendered,
            "// @generated by bench/build.rs for the ADR-0004 phf comparison.\n\n\
             /// Longest keyword spelling; sizes the phf lookup's lower-casing buffer.\n\
             pub const PHF_MAX_KEYWORD_LEN: usize = {max_len};\n\n\
             /// Perfect-hash keyword lookup over the lower-case spelling bytes, built\n\
             /// from the same inventory as the generated `lookup_keyword`.\n\
             pub static PHF_KEYWORDS: phf::Map<&'static [u8], Keyword> = {};\n",
            map.build(),
        )
        .expect("render phf map literal");
        fs::write(out.join("phf_keywords.rs"), rendered).expect("write phf_keywords.rs");
    }

    /// The checked-in keyword source data, under the workspace root one level up
    /// from this crate.
    fn workspace_keyword_data() -> std::path::PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("bench has a workspace root one level up")
            .join("crates/squonk-sourcegen/keyword_data")
    }
}
